import { Category, IProduct } from "@/types/product";



export const categories: Category[] = [
  { id: "1", name: "Electronics", slug: "electronics", icon: "📱" },
  { id: "2", name: "Fashion", slug: "fashion", icon: "👕" },
  { id: "3", name: "Home & Kitchen", slug: "home-kitchen", icon: "🏠" },
  { id: "4", name: "Beauty", slug: "beauty", icon: "💄" },
  { id: "5", name: "Sports", slug: "sports", icon: "⚽" },
  { id: "6", name: "Toys", slug: "toys", icon: "🧸" },
  { id: "7", name: "Books", slug: "books", icon: "📚" },
  { id: "8", name: "Gaming", slug: "gaming", icon: "🎮" },
];

export const products: IProduct[] = [
  // ----------------------------------------------------------------------
  // Electronics (with Subcategories)
  // ----------------------------------------------------------------------
  {
    "id": "1",
    "slug": "wireless-headphones",
    "title": "Premium Wireless Headphones with Active Noise Cancellation",
    "price": 299.00,
    "strikePrice": 499.00,
    "discount": "40% OFF",
    "category": "electronics",
    "subCategory": "Audio",
    "subCategorySlug": "audio",
    "image": "🎧",
    "badge": "Best Seller",
    "rating": 4.5,
    "inStock": true,
    "stockQuantity": 150,
    "sku": "ELEC-HP-001",
    "shortDescription": "Experience pure audio bliss with industry-leading noise cancellation and 40 hours of battery life. Perfect for travel and focus.",
    "longDescription": "These Premium Wireless Headphones deliver an immersive listening experience with advanced **Active Noise Cancellation (ANC)** technology. They feature **40mm dynamic drivers** for rich sound. The lightweight, ergonomic design ensures comfort for long sessions, and the massive battery provides up to 40 hours of playback. Comes with a premium carrying case and fast-charging support.",
    "specifications": [
      { "key": "Connection", "value": "Bluetooth 5.2 & Wired (3.5mm)" },
      { "key": "Feature", "value": "Active Noise Cancellation (ANC)" },
      { "key": "Battery Life", "value": "Up to 40 hours" },
      { "key": "Driver Size", "value": "40mm Dynamic" }
    ],
    "shippingAndReturns": { "shippingWeight": "0.45 kg", "deliveryTime": "2-4 Business Days", "returnPolicy": "30-Day Money-Back Guarantee" },
    "warranty": { "duration": "2 Years Manufacturer's Warranty", "coverage": "Parts and Labor" }
  },
  {
    "id": "2",
    "slug": "smart-watch",
    "title": "Smart Watch with Advanced Health Tracking",
    "price": 199.00,
    "strikePrice": 349.00,
    "discount": "43% OFF",
    "category": "electronics",
    "subCategory": "Wearables",
    "subCategorySlug": "wearables",
    "image": "⌚",
    "badge": "New Arrival",
    "rating": 4.3,
    "inStock": true,
    "stockQuantity": 120,
    "sku": "ELEC-SW-002",
    "shortDescription": "Stylish smartwatch featuring heart rate, blood oxygen monitoring, and GPS tracking. Long-lasting battery.",
    "longDescription": "Track your fitness goals and monitor essential health metrics with this versatile Smart Watch. It boasts a bright AMOLED display, advanced **HR and SpO2 sensors**, and built-in **GPS** for run tracking. Water-resistant design with multi-sport modes.",
    "specifications": [
      { "key": "Display", "value": "AMOLED Touchscreen" },
      { "key": "Features", "value": "HR, SpO2, Sleep Tracking, GPS" },
      { "key": "Water Resistance", "value": "5 ATM" },
      { "key": "Compatibility", "value": "iOS & Android" }
    ],
    "shippingAndReturns": { "shippingWeight": "0.15 kg", "deliveryTime": "2-4 Business Days", "returnPolicy": "30-Day Return Policy" },
    "warranty": { "duration": "1 Year Limited Warranty", "coverage": "Manufacturing Defects" }
  },
  {
    "id": "3",
    "slug": "bluetooth-speaker",
    "title": "Portable Bluetooth Speaker - Waterproof and Durable",
    "price": 89.00,
    "strikePrice": 149.00,
    "discount": "40% OFF",
    "category": "electronics",
    "subCategory": "Audio",
    "subCategorySlug": "audio",
    "image": "🔊",
    "rating": 4.6,
    "inStock": true,
    "stockQuantity": 250,
    "sku": "ELEC-BS-003",
    "shortDescription": "High-quality, rugged speaker with deep bass and 12-hour playtime. IPX7 waterproof rating.",
    "longDescription": "Take your music anywhere with this powerful and durable portable speaker. Features **12 hours of continuous playback** and a robust **IPX7 waterproof** rating, making it perfect for pool parties or beach trips. Delivers rich, 360-degree sound.",
    "specifications": [
      { "key": "Connectivity", "value": "Bluetooth 5.0" },
      { "key": "Waterproof Rating", "value": "IPX7" },
      { "key": "Playtime", "value": "Up to 12 hours" },
      { "key": "Audio Output", "value": "20W" }
    ],
    "shippingAndReturns": { "shippingWeight": "0.6 kg", "deliveryTime": "3-5 Business Days", "returnPolicy": "14-Day Return Policy" },
    "warranty": { "duration": "1 Year Warranty", "coverage": "Internal components" }
  },
  {
    "id": "4",
    "slug": "wireless-mouse",
    "title": "Ergonomic Wireless Mouse for Comfort and Precision",
    "price": 45.00,
    "strikePrice": 79.00,
    "discount": "43% OFF",
    "category": "electronics",
    "subCategory": "PC Accessories",
    "subCategorySlug": "pc-accessories",
    "image": "🖱️",
    "rating": 4.4,
    "inStock": true,
    "stockQuantity": 350,
    "sku": "ELEC-WM-004",
    "shortDescription": "Contoured shape and adjustable DPI for comfortable, precise control. Long-range wireless connection.",
    "longDescription": "Designed for long workdays, this ergonomic wireless mouse reduces strain with its sculpted shape. Features **adjustable DPI up to 2400** for precise tracking across different tasks and a reliable 2.4GHz wireless connection.",
    "specifications": [
      { "key": "Connectivity", "value": "2.4 GHz Wireless (USB Dongle)" },
      { "key": "DPI", "value": "800/1200/1600/2400 DPI" },
      { "key": "Design", "value": "Ergonomic, Right-Handed" },
      { "key": "Battery Type", "value": "AA (Included)" }
    ],
    "shippingAndReturns": { "shippingWeight": "0.1 kg", "deliveryTime": "2-4 Business Days", "returnPolicy": "30-Day Return Policy" },
    "warranty": { "duration": "1 Year Warranty", "coverage": "Hardware" }
  },
  {
    "id": "5",
    "slug": "mechanical-keyboard",
    "title": "RGB Mechanical Gaming Keyboard with Blue Switches",
    "price": 129.00,
    "strikePrice": 199.0    ,
    "discount": "35% OFF",
    "category": "electronics",
    "subCategory": "PC Accessories",
    "subCategorySlug": "pc-accessories",
    "image": "⌨️",
    "badge": "Hot Deal",
    "rating": 4.7,
    "inStock": true,
    "stockQuantity": 100,
    "sku": "ELEC-MK-005",
    "shortDescription": "Tactile and clicky Blue Switches, customizable RGB lighting, and anti-ghosting technology for gamers.",
    "longDescription": "The ultimate gaming keyboard featuring responsive **Blue Mechanical Switches** for a satisfying click and tactile bump. Full **RGB backlighting** is customizable per key. Includes N-Key Rollover (Anti-Ghosting) and a durable aluminum top plate.",
    "specifications": [
      { "key": "Switch Type", "value": "Mechanical (Blue)" },
      { "key": "Backlighting", "value": "Per-Key RGB" },
      { "key": "Key Rollover", "value": "N-Key Rollover (Anti-Ghosting)" },
      { "key": "Connection", "value": "Wired USB" }
    ],
    "shippingAndReturns": { "shippingWeight": "1.2 kg", "deliveryTime": "3-5 Business Days", "returnPolicy": "14-Day Return Policy" },
    "warranty": { "duration": "1 Year Warranty", "coverage": "Switches and Backlighting" }
  },
  {
    "id": "6",
    "slug": "laptop-stand",
    "title": "Adjustable Aluminum Laptop Stand for Ergonomics",
    "price": 39.00,
    "strikePrice": 69.00,
    "discount": "43% OFF",
    "category": "electronics",
    "subCategory": "PC Accessories",
    "subCategorySlug": "pc-accessories",
    "image": "💻",
    "rating": 4.5,
    "inStock": true,
    "stockQuantity": 400,
    "sku": "ELEC-LS-006",
    "shortDescription": "Sturdy, height-adjustable aluminum stand. Improves posture and provides optimal ventilation for laptops up to 17 inches.",
    "longDescription": "Elevate your laptop to eye level with this robust aluminum stand, promoting better posture and reducing neck strain. Its open design enhances **airflow and heat dissipation**. Compatible with most laptops from 10 to 17 inches.",
    "specifications": [
      { "key": "Material", "value": "High-Quality Aluminum Alloy" },
      { "key": "Compatibility", "value": "10\" to 17\" Laptops" },
      { "key": "Adjustability", "value": "Multiple Height Settings" },
      { "key": "Feature", "value": "Heat Dissipation Design" }
    ],
    "shippingAndReturns": { "shippingWeight": "0.8 kg", "deliveryTime": "2-4 Business Days", "returnPolicy": "30-Day Return Policy" },
    "warranty": { "duration": "6 Months Warranty", "coverage": "Structural Integrity" }
  },
  {
    "id": "7",
    "slug": "usb-hub",
    "title": "7-Port USB 3.0 Hub with Power Adapter",
    "price": 29.00,
    "strikePrice": 49.00,
    "discount": "41% OFF",
    "category": "electronics",
    "subCategory": "PC Accessories",
    "subCategorySlug": "pc-accessories",
    "image": "🔌",
    "rating": 4.2,
    "inStock": true,
    "stockQuantity": 280,
    "sku": "ELEC-UH-007",
    "shortDescription": "Expand your connectivity with seven high-speed USB 3.0 ports. Includes a dedicated power adapter for reliable data transfer.",
    "longDescription": "A reliable solution for expanding your device connectivity. This hub features **seven USB 3.0 ports** supporting speeds up to 5Gbps. Comes with an external power adapter to ensure stable performance for multiple high-power devices simultaneously.",
    "specifications": [
      { "key": "Ports", "value": "7 x USB 3.0" },
      { "key": "Data Speed", "value": "Up to 5 Gbps" },
      { "key": "Power", "value": "External Power Adapter Included" },
      { "key": "Feature", "value": "Individual On/Off Switches" }
    ],
    "shippingAndReturns": { "shippingWeight": "0.3 kg", "deliveryTime": "3-5 Business Days", "returnPolicy": "14-Day Return Policy" },
    "warranty": { "duration": "1 Year Warranty", "coverage": "Functionality" }
  },
  {
    "id": "8",
    "slug": "webcam-hd",
    "title": "1080p Full HD Webcam with Built-in Microphone",
    "price": 79.00,
    "strikePrice": 129.00,
    "discount": "39% OFF",
    "category": "electronics",
    "subCategory": "PC Accessories",
    "subCategorySlug": "pc-accessories",
    "image": "📷",
    "rating": 4.3,
    "inStock": true,
    "stockQuantity": 190,
    "sku": "ELEC-WC-008",
    "shortDescription": "Crystal-clear 1080p video quality for streaming and conferencing. Automatic light correction and noise-canceling mic.",
    "longDescription": "Perfect for remote work and video calls. This webcam delivers crisp **1080p resolution at 30fps**. It features **automatic low-light correction** and a **built-in noise-canceling microphone** to ensure you look and sound professional.",
    "specifications": [
      { "key": "Video Resolution", "value": "1080p Full HD @ 30fps" },
      { "key": "Field of View (FOV)", "value": "Wide 90-degree" },
      { "key": "Microphone", "value": "Built-in Noise-Canceling" },
      { "key": "Connection", "value": "Plug-and-Play USB" }
    ],
    "shippingAndReturns": { "shippingWeight": "0.12 kg", "deliveryTime": "2-4 Business Days", "returnPolicy": "30-Day Return Policy" },
    "warranty": { "duration": "1 Year Warranty", "coverage": "Image Sensor" }
  },

  // ----------------------------------------------------------------------
  // Fashion
  // ----------------------------------------------------------------------
  {
    "id": "9",
    "slug": "cotton-t-shirt",
    "title": "Premium Cotton T-Shirt - Pack of 3",
    "price": 59.00,
    "strikePrice": 99.00,
    "discount": "40% OFF",
    "category": "fashion",
    "subCategory": "Apparel",
    "subCategorySlug": "apparel",
    "image": "👕",
    "badge": "Popular",
    "rating": 4.4,
    "inStock": true,
    "stockQuantity": 500,
    "sku": "FASH-TS-009",
    "shortDescription": "Ultra-soft, breathable, 100% cotton crew-neck T-shirts. Essential wardrobe staple in three versatile colors.",
    "longDescription": "Get three essential T-shirts made from high-quality, pre-shrunk **100% combed cotton**. Designed for comfort and durability, these shirts retain their shape and color after multiple washes. Pack includes White, Black, and Heather Grey.",
    "specifications": [
      { "key": "Material", "value": "100% Combed Cotton" },
      { "key": "Fit", "value": "Regular Fit" },
      { "key": "Pack Size", "value": "Pack of 3" },
      { "key": "Available Sizes", "value": "S, M, L, XL, XXL" }
    ],
    "shippingAndReturns": { "shippingWeight": "0.5 kg", "deliveryTime": "3-6 Business Days", "returnPolicy": "Size exchange available within 15 days." },
    "warranty": { "duration": "N/A", "coverage": "N/A" }
  },
  {
    "id": "10",
    "slug": "denim-jeans",
    "title": "Slim Fit Stretch Denim Jeans",
    "price": 79.00,
    "strikePrice": 129.00,
    "discount": "39% OFF",
    "category": "fashion",
    "subCategory": "Apparel",
    "subCategorySlug": "apparel",
    "image": "👖",
    "rating": 4.5,
    "inStock": true,
    "stockQuantity": 320,
    "sku": "FASH-DJ-010",
    "shortDescription": "Modern slim-fit jeans with a hint of stretch for comfort and style. Classic 5-pocket design.",
    "longDescription": "These Slim Fit Jeans offer a contemporary look without sacrificing comfort. Made from a durable **cotton-spandex blend**, they provide just the right amount of stretch. Suitable for both casual and semi-formal wear.",
    "specifications": [
      { "key": "Material", "value": "98% Cotton, 2% Spandex" },
      { "key": "Fit", "value": "Slim Fit" },
      { "key": "Style", "value": "5-Pocket" },
      { "key": "Wash", "value": "Dark Indigo" }
    ],
    "shippingAndReturns": { "shippingWeight": "0.8 kg", "deliveryTime": "3-6 Business Days", "returnPolicy": "Size exchange available within 15 days." },
    "warranty": { "duration": "N/A", "coverage": "N/A" }
  },
  {
    "id": "11",
    "slug": "leather-jacket",
    "title": "Genuine Lambskin Leather Biker Jacket",
    "price": 249.00,
    "strikePrice": 399.00,
    "discount": "38% OFF",
    "category": "fashion",
    "subCategory": "Apparel",
    "subCategorySlug": "apparel",
    "image": "🧥",
    "badge": "Premium",
    "rating": 4.8,
    "inStock": true,
    "stockQuantity": 45,
    "sku": "FASH-LJ-011",
    "shortDescription": "A timeless Biker-style jacket crafted from premium genuine lambskin leather. Features a classic asymmetrical zip closure.",
    "longDescription": "Elevate your style with this exquisitely crafted **Genuine Lambskin Leather Jacket**. The lambskin provides a luxurious feel while ensuring a long lifespan. Features an asymmetrical **biker zip closure**, multiple functional pockets, and a quilted inner lining for comfort.",
    "specifications": [
      { "key": "Material", "value": "100% Genuine Lambskin Leather" },
      { "key": "Lining", "value": "Polyester Quilted Lining" },
      { "key": "Fit", "value": "Slim Fit" },
      { "key": "Available Sizes", "value": "S to XXL" }
    ],
    "shippingAndReturns": { "shippingWeight": "1.5 kg", "deliveryTime": "3-6 Business Days", "returnPolicy": "Size exchange or return accepted within 15 days." },
    "warranty": { "duration": "6 Months Material and Workmanship Warranty", "coverage": "Stitching and Zippers" }
  },
  {
    "id": "12",
    "slug": "running-shoes",
    "title": "Professional Lightweight Running Shoes",
    "price": 129.00,
    "strikePrice": 199.00,
    "discount": "35% OFF",
    "category": "fashion",
    "subCategory": "Footwear",
    "subCategorySlug": "footwear",
    "image": "👟",
    "badge": "Best Seller",
    "rating": 4.6,
    "inStock": true,
    "stockQuantity": 210,
    "sku": "FASH-RS-012",
    "shortDescription": "Lightweight running shoes with responsive cushioning and breathable mesh upper. Ideal for long-distance runners.",
    "longDescription": "Engineered for speed and endurance, these shoes feature a responsive foam midsole for energy return and a seamless, breathable mesh upper for maximum airflow. Durable rubber outsole provides reliable traction.",
    "specifications": [
      { "key": "Upper Material", "value": "Breathable Mesh" },
      { "key": "Cushioning", "value": "Responsive Foam Midsole" },
      { "key": "Support Type", "value": "Neutral" },
      { "key": "Closure", "value": "Lace-up" }
    ],
    "shippingAndReturns": { "shippingWeight": "1.0 kg", "deliveryTime": "4-7 Business Days", "returnPolicy": "30-Day return/exchange for unused items." },
    "warranty": { "duration": "N/A", "coverage": "N/A" }
  },
  {
    "id": "13",
    "slug": "casual-sneakers",
    "title": "Comfortable Canvas Casual Sneakers",
    "price": 89.00,
    "strikePrice": 149.00,
    "discount": "40% OFF",
    "category": "fashion",
    "subCategory": "Footwear",
    "subCategorySlug": "footwear",
    "image": "👞",
    "rating": 4.4,
    "inStock": true,
    "stockQuantity": 180,
    "sku": "FASH-CS-013",
    "shortDescription": "Classic low-top canvas sneakers designed for all-day comfort and versatile styling.",
    "longDescription": "The quintessential casual shoe. Made with a durable canvas upper and a cushioned insole. The rubber outsole provides good grip, and the simple design pairs well with jeans, shorts, or casual dresses.",
    "specifications": [
      { "key": "Material", "value": "Canvas Upper, Rubber Sole" },
      { "key": "Style", "value": "Low-Top" },
      { "key": "Insole", "value": "Cushioned Comfort" },
      { "key": "Color Options", "value": "White, Navy, Black" }
    ],
    "shippingAndReturns": { "shippingWeight": "0.7 kg", "deliveryTime": "3-6 Business Days", "returnPolicy": "30-Day return/exchange for unused items." },
    "warranty": { "duration": "N/A", "coverage": "N/A" }
  },
  {
    "id": "14",
    "slug": "sports-cap",
    "title": "Adjustable Moisture-Wicking Sports Cap",
    "price": 25.00,
    "strikePrice": 39.00,
    "discount": "36% OFF",
    "category": "fashion",
    "subCategory": "Accessories",
    "subCategorySlug": "accessories",
    "image": "🧢",
    "rating": 4.2,
    "inStock": true,
    "stockQuantity": 450,
    "sku": "FASH-SC-014",
    "shortDescription": "Lightweight, quick-drying cap with an adjustable strap. Perfect for running, golf, or casual sun protection.",
    "longDescription": "This sports cap is made from a performance fabric that **wicks away moisture** to keep you cool and dry. Features an adjustable strap for a custom fit and a pre-curved visor to shield your eyes.",
    "specifications": [
      { "key": "Material", "value": "Polyester Mesh Blend" },
      { "key": "Feature", "value": "Moisture-Wicking, Quick-Dry" },
      { "key": "Size", "value": "One Size Fits Most (Adjustable)" },
      { "key": "Use", "value": "Running, Training, Casual" }
    ],
    "shippingAndReturns": { "shippingWeight": "0.1 kg", "deliveryTime": "2-5 Business Days", "returnPolicy": "14-Day Return Policy" },
    "warranty": { "duration": "N/A", "coverage": "N/A" }
  },
  {
    "id": "15",
    "slug": "backpack",
    "title": "Water Resistant Travel & Laptop Backpack",
    "price": 69.00,
    "strikePrice": 119.00,
    "discount": "42% OFF",
    "category": "fashion",
    "subCategory": "Accessories",
    "subCategorySlug": "accessories",
    "image": "🎒",
    "rating": 4.7,
    "inStock": true,
    "stockQuantity": 110,
    "sku": "FASH-BP-015",
    "shortDescription": "Spacious and durable backpack with a dedicated laptop compartment and water-resistant exterior for daily commute or travel.",
    "longDescription": "Designed for organization and protection. Features a padded sleeve that fits up to a 15.6-inch laptop, multiple interior pockets, and a **water-resistant Oxford fabric** exterior. Ergonomic shoulder straps provide all-day comfort.",
    "specifications": [
      { "key": "Capacity", "value": "25 Liters" },
      { "key": "Material", "value": "Water-Resistant Oxford Fabric" },
      { "key": "Laptop Sleeve", "value": "Fits up to 15.6 inches" },
      { "key": "Feature", "value": "Hidden Anti-Theft Pocket" }
    ],
    "shippingAndReturns": { "shippingWeight": "0.9 kg", "deliveryTime": "3-6 Business Days", "returnPolicy": "30-Day Return Policy" },
    "warranty": { "duration": "1 Year Warranty", "coverage": "Zippers and Material Defects" }
  },
  {
    "id": "16",
    "slug": "sunglasses",
    "title": "Polarized UV Protection Sunglasses (Classic Design)",
    "price": 49.00,
    "strikePrice": 89.00,
    "discount": "45% OFF",
    "category": "fashion",
    "subCategory": "Accessories",
    "subCategorySlug": "accessories",
    "image": "🕶️",
    "badge": "Hot Deal",
    "rating": 4.5,
    "inStock": true,
    "stockQuantity": 160,
    "sku": "FASH-SG-016",
    "shortDescription": "Classic style sunglasses with polarized lenses offering 100% UV400 protection.",
    "longDescription": "Protect your eyes in style. The **polarized lenses** reduce glare for better clarity, while the **UV400 coating** blocks 100% of harmful UVA and UVB rays. Durable frame with comfortable fit.",
    "specifications": [
      { "key": "Lens Technology", "value": "Polarized, UV400 Protection" },
      { "key": "Frame Material", "value": "Polycarbonate" },
      { "key": "Style", "value": "Classic Aviator/Wayfarer" },
      { "key": "Gender", "value": "Unisex" }
    ],
    "shippingAndReturns": { "shippingWeight": "0.05 kg", "deliveryTime": "2-5 Business Days", "returnPolicy": "14-Day Return Policy" },
    "warranty": { "duration": "N/A", "coverage": "N/A" }
  },

  // ----------------------------------------------------------------------
  // Home & Kitchen
  // ----------------------------------------------------------------------
  {
    "id": "17",
    "slug": "coffee-maker",
    "title": "Automatic Drip Coffee Maker Machine",
    "price": 159.00,
    "strikePrice": 249.00,
    "discount": "36% OFF",
    "category": "home-kitchen",
    "subCategory": "Appliances",
    "subCategorySlug": "appliances",
    "image": "☕",
    "badge": "Best Seller",
    "rating": 4.6,
    "inStock": true,
    "stockQuantity": 90,
    "sku": "HK-CM-017",
    "shortDescription": "Programmable 12-cup drip coffee maker with a keep-warm function and anti-drip system.",
    "longDescription": "Start your day right with freshly brewed coffee. This fully **programmable** drip coffee maker allows you to set the brew time in advance. Features a **12-cup capacity** glass carafe and a non-stick warming plate to keep coffee hot.",
    "specifications": [
      { "key": "Capacity", "value": "12 Cups" },
      { "key": "Features", "value": "Programmable Timer, Keep Warm Function" },
      { "key": "Carafe Material", "value": "Glass" },
      { "key": "Power", "value": "900 Watts" }
    ],
    "shippingAndReturns": { "shippingWeight": "3.0 kg", "deliveryTime": "3-7 Business Days", "returnPolicy": "30-Day Return Policy" },
    "warranty": { "duration": "1 Year Limited Warranty", "coverage": "Electrical Components" }
  },
  {
    "id": "18",
    "slug": "blender",
    "title": "High-Speed Countertop Blender 1200W",
    "price": 119.00,
    "strikePrice": 199.00,
    "discount": "40% OFF",
    "category": "home-kitchen",
    "subCategory": "Appliances",
    "subCategorySlug": "appliances",
    "image": "🥤",
    "rating": 4.5,
    "inStock": true,
    "stockQuantity": 130,
    "sku": "HK-BL-018",
    "shortDescription": "Powerful 1200-watt motor and hardened stainless steel blades, perfect for smoothies, ice crushing, and soups.",
    "longDescription": "Effortlessly blend fruits, vegetables, and ice with the powerful **1200W motor**. Comes with a large, durable Tritan pitcher and pre-programmed settings for smoothies and crushed ice. Easy to clean.",
    "specifications": [
      { "key": "Motor Power", "value": "1200 Watts" },
      { "key": "Pitcher Material", "value": "BPA-Free Tritan" },
      { "key": "Capacity", "value": "1.5 Liters" },
      { "key": "Settings", "value": "Pulse, Smoothie, Ice Crush" }
    ],
    "shippingAndReturns": { "shippingWeight": "4.5 kg", "deliveryTime": "3-7 Business Days", "returnPolicy": "30-Day Return Policy" },
    "warranty": { "duration": "2 Years Limited Warranty", "coverage": "Motor" }
  },
  {
    "id": "19",
    "slug": "cookware-set",
    "title": "Non-Stick Cookware Set - 10 Pieces",
    "price": 179.00,
    "strikePrice": 299.00,
    "discount": "40% OFF",
    "category": "home-kitchen",
    "subCategory": "Cookware",
    "subCategorySlug": "cookware",
    "image": "🍳",
    "badge": "Popular",
    "rating": 4.7,
    "inStock": true,
    "stockQuantity": 75,
    "sku": "HK-CS-019",
    "shortDescription": "Durable 10-piece non-stick set including fry pans, saucepans, and Dutch oven. PFOA-free.",
    "longDescription": "A complete set for any home cook. Featuring a reinforced, **PFOA-free non-stick coating** for easy cooking and cleanup. Induction compatible and oven safe up to 350°F. Includes tempered glass lids with steam vents.",
    "specifications": [
      { "key": "Pieces", "value": "10 Pieces (Pans, Pots, Lids)" },
      { "key": "Coating", "value": "PFOA-Free Non-Stick" },
      { "key": "Compatibility", "value": "Gas, Electric, Induction" },
      { "key": "Color", "value": "Graphite Grey" }
    ],
    "shippingAndReturns": { "shippingWeight": "8.0 kg", "deliveryTime": "4-7 Business Days", "returnPolicy": "30-Day Return Policy" },
    "warranty": { "duration": "5 Years Limited Warranty", "coverage": "Non-Stick Coating" }
  },
  {
    "id": "20",
    "slug": "vacuum-cleaner",
    "title": "Cordless Stick Vacuum Cleaner with HEPA Filtration",
    "price": 229.00,
    "strikePrice": 379.00,
    "discount": "40% OFF",
    "category": "home-kitchen",
    "subCategory": "Appliances",
    "subCategorySlug": "appliances",
    "image": "🧹",
    "badge": "New Arrival",
    "rating": 4.6,
    "inStock": true,
    "stockQuantity": 80,
    "sku": "HK-VC-020",
    "shortDescription": "Lightweight, powerful cordless vacuum with long battery life and an advanced HEPA filtration system.",
    "longDescription": "Enjoy hassle-free cleaning with this versatile cordless vacuum. Features strong suction power, up to **40 minutes of runtime**, and a **HEPA filter** to capture fine dust and allergens. Easily converts to a handheld vacuum.",
    "specifications": [
      { "key": "Type", "value": "Cordless Stick/Handheld" },
      { "key": "Run Time", "value": "Up to 40 Minutes" },
      { "key": "Filtration", "value": "Washable HEPA Filter" },
      { "key": "Weight", "value": "2.5 kg (Lightweight)" }
    ],
    "shippingAndReturns": { "shippingWeight": "4.0 kg", "deliveryTime": "4-7 Business Days", "returnPolicy": "30-Day Return Policy" },
    "warranty": { "duration": "2 Years Limited Warranty", "coverage": "Motor and Battery" }
  },
  {
    "id": "21",
    "slug": "air-fryer",
    "title": "Digital Air Fryer 5.5L - Oil-Free Cooking",
    "price": 149.00,
    "strikePrice": 249.00,
    "discount": "40% OFF",
    "category": "home-kitchen",
    "subCategory": "Appliances",
    "subCategorySlug": "appliances",
    "image": "🍟",
    "badge": "Hot Deal",
    "rating": 4.8,
    "inStock": true,
    "stockQuantity": 120,
    "sku": "HK-AFR-001",
    "shortDescription": "Cook healthy, crispy meals with 90% less oil. Features 7 preset cooking modes and an easy-to-use digital touchscreen.",
    "longDescription": "The Digital Air Fryer uses **rapid hot air circulation** to cook your favorite foods to a perfect crisp without excess oil. With a generous **5.5 Liter capacity**, it's ideal for family meals. The intuitive digital touchscreen offers **7 one-touch preset programs**. Cleanup is easy with the **non-stick, dishwasher-safe basket**.",
    "specifications": [
      { "key": "Capacity", "value": "5.5 Liters" },
      { "key": "Power", "value": "1500 Watts" },
      { "key": "Control", "value": "Digital Touchscreen" },
      { "key": "Temperature Range", "value": "80°C to 200°C" }
    ],
    "shippingAndReturns": { "shippingWeight": "6.0 kg", "deliveryTime": "3-7 Business Days", "returnPolicy": "Standard 30-Day Return Policy" },
    "warranty": { "duration": "1 Year Limited Warranty", "coverage": "Motor and Electrical Components" }
  },
  {
    "id": "22",
    "slug": "knife-set",
    "title": "Professional Chef Knife Set - 8 Pieces",
    "price": 89.00,
    "strikePrice": 149.00,
    "discount": "40% OFF",
    "category": "home-kitchen",
    "subCategory": "Cutlery",
    "subCategorySlug": "cutlery",
    "image": "🔪",
    "rating": 4.5,
    "inStock": true,
    "stockQuantity": 105,
    "sku": "HK-KS-022",
    "shortDescription": "8-piece set of high-carbon stainless steel knives in a stylish wooden block. Essential for every kitchen.",
    "longDescription": "Precision-forged from durable **high-carbon stainless steel**, these knives are sharp, rust-resistant, and balanced for comfortable cutting. Set includes Chef's, Santoku, Utility, and Paring knives, plus a sharpening steel and wooden block.",
    "specifications": [
      { "key": "Pieces", "value": "8 (Knives + Block + Sharpener)" },
      { "key": "Material", "value": "High-Carbon Stainless Steel" },
      { "key": "Handle", "value": "Ergonomic Polymer" },
      { "key": "Maintenance", "value": "Hand Wash Recommended" }
    ],
    "shippingAndReturns": { "shippingWeight": "3.5 kg", "deliveryTime": "3-6 Business Days", "returnPolicy": "30-Day Return Policy" },
    "warranty": { "duration": "5 Years Limited Warranty", "coverage": "Blades and Handles" }
  },
  {
    "id": "23",
    "slug": "cutting-board",
    "title": "Natural Bamboo Cutting Board Set - 3pc",
    "price": 35.00,
    "strikePrice": 59.00,
    "discount": "41% OFF",
    "category": "home-kitchen",
    "subCategory": "Utensils",
    "subCategorySlug": "utensils",
    "image": "🪵",
    "rating": 4.4,
    "inStock": true,
    "stockQuantity": 180,
    "sku": "HK-CB-023",
    "shortDescription": "Set of three durable, anti-microbial bamboo cutting boards (small, medium, large). Gentle on knives.",
    "longDescription": "Made from environmentally friendly **natural bamboo**, these boards are lightweight, durable, and naturally **anti-microbial**. Set includes three sizes for different tasks, each featuring a juice groove to prevent countertop mess.",
    "specifications": [
      { "key": "Material", "value": "Natural Bamboo" },
      { "key": "Set Size", "value": "3 Pieces (S, M, L)" },
      { "key": "Feature", "value": "Juice Groove, Anti-Microbial" },
      { "key": "Care", "value": "Hand Wash" }
    ],
    "shippingAndReturns": { "shippingWeight": "1.8 kg", "deliveryTime": "3-6 Business Days", "returnPolicy": "30-Day Return Policy" },
    "warranty": { "duration": "N/A", "coverage": "N/A" }
  },
  {
    "id": "24",
    "slug": "food-storage",
    "title": "Glass Food Storage Containers - 12pc Set",
    "price": 59.00,
    "strikePrice": 99.00,
    "discount": "40% OFF",
    "category": "home-kitchen",
    "subCategory": "Storage",
    "subCategorySlug": "storage",
    "image": "🥫",
    "rating": 4.6,
    "inStock": true,
    "stockQuantity": 150,
    "sku": "HK-FS-024",
    "shortDescription": "12-piece set of airtight, oven-safe glass containers with locking lids. BPA-free.",
    "longDescription": "Keep food fresh longer with these versatile glass containers. They are **oven, microwave, and freezer safe**, and come with BPA-free, leak-proof locking lids. Perfect for meal prepping and leftovers.",
    "specifications": [
      { "key": "Pieces", "value": "12 (6 Containers, 6 Lids)" },
      { "key": "Material", "value": "High Borosilicate Glass, BPA-Free Lids" },
      { "key": "Safety", "value": "Oven, Microwave, Freezer, Dishwasher Safe" },
      { "key": "Lid Type", "value": "Airtight Locking" }
    ],
    "shippingAndReturns": { "shippingWeight": "4.2 kg", "deliveryTime": "3-7 Business Days", "returnPolicy": "30-Day Return Policy" },
    "warranty": { "duration": "N/A", "coverage": "N/A" }
  },

  // ----------------------------------------------------------------------
  // Beauty
  // ----------------------------------------------------------------------
  {
    "id": "25",
    "slug": "skincare-set",
    "title": "Complete Hydrating Skincare Set - 5 Products",
    "price": 129.00,
    "strikePrice": 219.00,
    "discount": "41% OFF",
    "category": "beauty",
    "subCategory": "Skincare",
    "subCategorySlug": "skincare",
    "image": "💆",
    "badge": "Best Seller",
    "rating": 4.7,
    "inStock": true,
    "stockQuantity": 90,
    "sku": "BEAUTY-SK-001",
    "shortDescription": "A 5-piece set for a complete morning and evening routine, featuring Hyaluronic Acid and Vitamin C for glowing, hydrated skin.",
    "longDescription": "Achieve your best skin with this essential 5-piece set designed for daily hydration and rejuvenation. The set includes a **Gentle Cleanser**, **Vitamin C Serum**, **Hyaluronic Acid Moisturizer**, **Eye Cream**, and an **Overnight Sleeping Mask**. All products are **paraben-free, cruelty-free**, and suitable for all skin types.",
    "specifications": [
      { "key": "Set Contents", "value": "Cleanser, Serum, Moisturizer, Eye Cream, Mask" },
      { "key": "Key Ingredients", "value": "Hyaluronic Acid, Vitamin C" },
      { "key": "Skin Type", "value": "All Skin Types" },
      { "key": "Certifications", "value": "Cruelty-Free, Paraben-Free" }
    ],
    "shippingAndReturns": { "shippingWeight": "0.7 kg", "deliveryTime": "2-5 Business Days", "returnPolicy": "Returns accepted if unopened and unused within 30 days." },
    "warranty": { "duration": "N/A", "coverage": "Satisfaction Guarantee" }
  },
  {
    "id": "26",
    "slug": "makeup-brush-set",
    "title": "Professional Makeup Brush Set - 12pc",
    "price": 49.00,
    "strikePrice": 89.00,
    "discount": "45% OFF",
    "category": "beauty",
    "subCategory": "Makeup",
    "subCategorySlug": "makeup",
    "image": "💄",
    "rating": 4.5,
    "inStock": true,
    "stockQuantity": 160,
    "sku": "BEAUTY-MB-026",
    "shortDescription": "12 essential brushes for face and eyes. Made with ultra-soft synthetic fibers and wooden handles.",
    "longDescription": "This professional-grade set includes brushes for foundation, powder, blush, contouring, and eyeshadow. The dense, **synthetic bristles** are cruelty-free and designed for flawless product application. Comes with a travel pouch.",
    "specifications": [
      { "key": "Quantity", "value": "12 Brushes" },
      { "key": "Bristle Material", "value": "Premium Synthetic Fiber" },
      { "key": "Handle Material", "value": "Wood" },
      { "key": "Feature", "value": "Cruelty-Free" }
    ],
    "shippingAndReturns": { "shippingWeight": "0.3 kg", "deliveryTime": "2-5 Business Days", "returnPolicy": "14-Day Return Policy" },
    "warranty": { "duration": "N/A", "coverage": "N/A" }
  },
  {
    "id": "27",
    "slug": "hair-dryer",
    "title": "Ionic Hair Dryer with Diffuser and Concentrator Nozzles",
    "price": 89.00,
    "strikePrice": 149.00,
    "discount": "40% OFF",
    "category": "beauty",
    "subCategory": "Hair Care Tools",
    "subCategorySlug": "hair-care-tools",
    "image": "💇",
    "badge": "Popular",
    "rating": 4.6,
    "inStock": true,
    "stockQuantity": 110,
    "sku": "BEAUTY-HD-027",
    "shortDescription": "Powerful 1875W ionic dryer. Reduces frizz and drying time with multiple heat/speed settings.",
    "longDescription": "The **ionic technology** seals the hair cuticle, reducing frizz and boosting shine. Features a powerful 1875W motor, 3 heat settings, and 2 speed settings. Includes a diffuser for curly hair and a concentrator for sleek styling.",
    "specifications": [
      { "key": "Power", "value": "1875 Watts" },
      { "key": "Technology", "value": "Ionic" },
      { "key": "Settings", "value": "3 Heat, 2 Speed, Cool Shot" },
      { "key": "Attachments", "value": "Diffuser, Concentrator" }
    ],
    "shippingAndReturns": { "shippingWeight": "1.0 kg", "deliveryTime": "3-6 Business Days", "returnPolicy": "30-Day Return Policy" },
    "warranty": { "duration": "1 Year Limited Warranty", "coverage": "Motor Failure" }
  },
  {
    "id": "28",
    "slug": "perfume-set",
    "title": "Luxury Eau de Parfum Gift Set - 3 Scents",
    "price": 179.00,
    "strikePrice": 299.00,
    "discount": "40% OFF",
    "category": "beauty",
    "subCategory": "Fragrance",
    "subCategorySlug": "fragrance",
    "image": "🌸",
    "badge": "Premium",
    "rating": 4.8,
    "inStock": true,
    "stockQuantity": 60,
    "sku": "BEAUTY-PF-028",
    "shortDescription": "An exquisite gift set featuring three signature long-lasting Eau de Parfum scents (Floral, Woody, Citrus).",
    "longDescription": "Experience three luxurious scents in one beautifully packaged gift set. Each **Eau de Parfum** is crafted with high-quality oils for maximum longevity. Perfect for gifting or trying out different fragrances for every occasion.",
    "specifications": [
      { "key": "Type", "value": "Eau de Parfum (EDP)" },
      { "key": "Quantity", "value": "3 x 50ml Bottles" },
      { "key": "Notes", "value": "Floral, Woody, Citrus" },
      { "key": "Longevity", "value": "8+ Hours" }
    ],
    "shippingAndReturns": { "shippingWeight": "0.8 kg", "deliveryTime": "3-6 Business Days", "returnPolicy": "No returns on opened perfume due to hygiene." },
    "warranty": { "duration": "N/A", "coverage": "N/A" }
  },
  {
    "id": "29",
    "slug": "face-mask-set",
    "title": "Hydrating Sheet Face Mask Set - 10pc",
    "price": 39.00,
    "strikePrice": 69.00,
    "discount": "43% OFF",
    "category": "beauty",
    "subCategory": "Skincare",
    "subCategorySlug": "skincare",
    "image": "🧖",
    "rating": 4.4,
    "inStock": true,
    "stockQuantity": 250,
    "sku": "BEAUTY-FM-029",
    "shortDescription": "A 10-pack of ultra-hydrating sheet masks infused with serum for glowing and supple skin.",
    "longDescription": "Quickly boost your skin's moisture barrier with these sheet masks. Each mask is saturated with a potent serum containing **Hyaluronic Acid and Collagen**. Suitable for all skin types. Use 2-3 times per week for best results.",
    "specifications": [
      { "key": "Quantity", "value": "10 Sheet Masks" },
      { "key": "Key Ingredients", "value": "Hyaluronic Acid, Collagen" },
      { "key": "Feature", "value": "Paraben-Free" },
      { "key": "Use Time", "value": "15-20 Minutes" }
    ],
    "shippingAndReturns": { "shippingWeight": "0.4 kg", "deliveryTime": "2-5 Business Days", "returnPolicy": "No returns on single masks." },
    "warranty": { "duration": "N/A", "coverage": "N/A" }
  },
  {
    "id": "30",
    "slug": "nail-polish-set",
    "title": "Long-Lasting Gel Nail Polish Set - 8 Colors",
    "price": 45.00,
    "strikePrice": 79.00,
    "discount": "43% OFF",
    "category": "beauty",
    "subCategory": "Makeup",
    "subCategorySlug": "makeup",
    "image": "💅",
    "rating": 4.3,
    "inStock": true,
    "stockQuantity": 170,
    "sku": "BEAUTY-NP-030",
    "shortDescription": "8 vibrant, chip-resistant gel polishes requiring a UV/LED lamp. Provides a high-gloss, salon-quality finish.",
    "longDescription": "Achieve a professional manicure at home. This set includes 8 trend-setting colors. The gel formula cures under a UV/LED lamp for a high-shine, chip-free finish that lasts up to 14 days. **Toxin-free formula**.",
    "specifications": [
      { "key": "Type", "value": "UV/LED Gel Polish" },
      { "key": "Quantity", "value": "8 Bottles" },
      { "key": "Feature", "value": "Chip-Resistant, Toxin-Free" },
      { "key": "Finish", "value": "High-Gloss" }
    ],
    "shippingAndReturns": { "shippingWeight": "0.3 kg", "deliveryTime": "3-6 Business Days", "returnPolicy": "14-Day Return Policy" },
    "warranty": { "duration": "N/A", "coverage": "N/A" }
  },
  {
    "id": "31",
    "slug": "electric-shaver",
    "title": "Rechargeable Wet & Dry Electric Shaver",
    "price": 99.00,
    "strikePrice": 169.00,
    "discount": "41% OFF",
    "category": "beauty",
    "subCategory": "Grooming Tools",
    "subCategorySlug": "grooming-tools",
    "image": "🪒",
    "rating": 4.5,
    "inStock": true,
    "stockQuantity": 85,
    "sku": "BEAUTY-ES-031",
    "shortDescription": "Versatile wet and dry electric shaver with a precision trimmer and long-lasting lithium battery.",
    "longDescription": "Provides a close, comfortable shave wet or dry. The flexible pivoting head adjusts to facial contours, and the integrated precision trimmer is perfect for sideburns and detailing. **Quick-charge** lithium-ion battery offers 60 minutes of cordless runtime.",
    "specifications": [
      { "key": "Use", "value": "Wet & Dry" },
      { "key": "Battery", "value": "Lithium-ion (60 min runtime)" },
      { "key": "Feature", "value": "Pivoting Head, Precision Trimmer" },
      { "key": "Charge Time", "value": "1 Hour" }
    ],
    "shippingAndReturns": { "shippingWeight": "0.5 kg", "deliveryTime": "3-6 Business Days", "returnPolicy": "30-Day Return Policy" },
    "warranty": { "duration": "2 Years Limited Warranty", "coverage": "Motor and Blades" }
  },
  {
    "id": "32",
    "slug": "makeup-mirror",
    "title": "LED Makeup Mirror with 3X Magnification",
    "price": 59.00,
    "strikePrice": 99.00,
    "discount": "40% OFF",
    "category": "beauty",
    "subCategory": "Grooming Tools",
    "subCategorySlug": "grooming-tools",
    "image": "🪞",
    "rating": 4.6,
    "inStock": true,
    "stockQuantity": 130,
    "sku": "BEAUTY-MM-032",
    "shortDescription": "Adjustable vanity mirror with bright natural LED lighting and a removable 3X magnification spot mirror.",
    "longDescription": "This mirror features ring-shaped **LED lighting** that simulates natural daylight, essential for flawless makeup application. The adjustable stand and integrated 3X magnification detail mirror make precision tasks easy. Battery and USB powered.",
    "specifications": [
      { "key": "Lighting", "value": "Natural Daylight LED" },
      { "key": "Magnification", "value": "Standard + 3X Spot" },
      { "key": "Power", "value": "Battery/USB" },
      { "key": "Adjustability", "value": "360° Swivel" }
    ],
    "shippingAndReturns": { "shippingWeight": "1.1 kg", "deliveryTime": "3-6 Business Days", "returnPolicy": "30-Day Return Policy" },
    "warranty": { "duration": "1 Year Limited Warranty", "coverage": "LED Lights" }
  },

  // ----------------------------------------------------------------------
  // Sports
  // ----------------------------------------------------------------------
  {
    "id": "33",
    "slug": "yoga-mat",
    "title": "Premium Extra Thick Non-Slip Yoga Mat (TPE Material)",
    "price": 39.00,
    "strikePrice": 69.00,
    "discount": "43% OFF",
    "category": "sports",
    "subCategory": "Fitness Gear",
    "subCategorySlug": "fitness-gear",
    "image": "🧘",
    "badge": "Best Seller",
    "rating": 4.7,
    "inStock": true,
    "stockQuantity": 200,
    "sku": "SPORT-YM-001",
    "shortDescription": "Eco-friendly, 6mm thick TPE mat providing superior cushioning and exceptional grip for yoga, Pilates, and general fitness.",
    "longDescription": "Our Premium Yoga Mat is constructed from high-density, eco-friendly **TPE (Thermoplastic Elastomer)** material. The **6mm thickness** offers the perfect balance between cushioning for joints and stability for poses. Its double-sided texture ensures a **non-slip grip**.",
    "specifications": [
      { "key": "Material", "value": "Eco-Friendly TPE" },
      { "key": "Thickness", "value": "6 mm (Extra Thick)" },
      { "key": "Dimensions", "value": "183 cm x 61 cm (72\" x 24\")" },
      { "key": "Feature", "value": "Double-Sided Non-Slip Texture" }
    ],
    "shippingAndReturns": { "shippingWeight": "1.2 kg", "deliveryTime": "3-5 Business Days", "returnPolicy": "30-Day Return for unused items." },
    "warranty": { "duration": "6 Months Product Quality Warranty", "coverage": "Tearing/Splitting under normal use" }
  },
  {
    "id": "34",
    "slug": "dumbbell-set",
    "title": "Adjustable Dumbbell Set - 20kg",
    "price": 119.00,
    "strikePrice": 199.00,
    "discount": "40% OFF",
    "category": "sports",
    "subCategory": "Weightlifting",
    "subCategorySlug": "weightlifting",
    "image": "🏋️",
    "rating": 4.6,
    "inStock": true,
    "stockQuantity": 80,
    "sku": "SPORT-DB-034",
    "shortDescription": "Versatile adjustable dumbbell set, ranging from 2.5kg to 20kg. Ideal for home strength training.",
    "longDescription": "This set allows for quick weight changes using a secure locking collar system, eliminating the need for multiple dumbbells. The plates are made from durable cast iron with a rust-resistant coating. Total weight: **20kg (44 lbs)**.",
    "specifications": [
      { "key": "Weight Range", "value": "2.5 kg to 20 kg (Adjustable)" },
      { "key": "Material", "value": "Cast Iron Plates, Steel Bar" },
      { "key": "Grip", "value": "Non-Slip Knurled Handle" },
      { "key": "Set Includes", "value": "4 x 2.5kg, 4 x 1.25kg, 2 Bars, 4 Collars" }
    ],
    "shippingAndReturns": { "shippingWeight": "20.5 kg", "deliveryTime": "5-10 Business Days", "returnPolicy": "30-Day Return Policy" },
    "warranty": { "duration": "1 Year Limited Warranty", "coverage": "Plates and Bar" }
  },
  {
    "id": "35",
    "slug": "resistance-bands",
    "title": "Resistance Bands Set - 5 Levels",
    "price": 29.00,
    "strikePrice": 49.00,
    "discount": "41% OFF",
    "category": "sports",
    "subCategory": "Fitness Gear",
    "subCategorySlug": "fitness-gear",
    "image": "🎯",
    "rating": 4.5,
    "inStock": true,
    "stockQuantity": 300,
    "sku": "SPORT-RB-035",
    "shortDescription": "Set of 5 durable latex resistance loops with varying tension levels for full-body workouts and physical therapy.",
    "longDescription": "These versatile bands come in 5 color-coded resistance levels (X-Light to X-Heavy), suitable for all fitness levels. Made from 100% natural, skin-friendly latex. Includes a carrying bag and exercise guide.",
    "specifications": [
      { "key": "Quantity", "value": "5 Bands" },
      { "key": "Material", "value": "100% Natural Latex" },
      { "key": "Resistance Levels", "value": "X-Light, Light, Medium, Heavy, X-Heavy" },
      { "key": "Feature", "value": "Includes Carry Bag" }
    ],
    "shippingAndReturns": { "shippingWeight": "0.2 kg", "deliveryTime": "2-5 Business Days", "returnPolicy": "30-Day Return Policy" },
    "warranty": { "duration": "N/A", "coverage": "N/A" }
  },
  {
    "id": "36",
    "slug": "soccer-ball",
    "title": "Professional Thermal Bonded Soccer Ball (Size 5)",
    "price": 45.00,
    "strikePrice": 79.00,
    "discount": "43% OFF",
    "category": "sports",
    "subCategory": "Team Sports",
    "subCategorySlug": "team-sports",
    "image": "⚽",
    "rating": 4.4,
    "inStock": true,
    "stockQuantity": 150,
    "sku": "SPORT-SB-036",
    "shortDescription": "Official size 5 soccer ball with thermal-bonded construction for reduced water absorption and consistent flight.",
    "longDescription": "Engineered for high-level performance. The **thermal-bonded panel construction** provides a smooth, seamless surface for predictable trajectory and high durability. Suitable for all playing surfaces (turf, grass, artificial).",
    "specifications": [
      { "key": "Size", "value": "Size 5 (Official Match)" },
      { "key": "Construction", "value": "Thermal Bonded" },
      { "key": "Outer Material", "value": "PU Synthetic Leather" },
      { "key": "Bladder", "value": "Butyl Bladder" }
    ],
    "shippingAndReturns": { "shippingWeight": "0.45 kg", "deliveryTime": "3-6 Business Days", "returnPolicy": "14-Day Return Policy" },
    "warranty": { "duration": "N/A", "coverage": "N/A" }
  },
  {
    "id": "37",
    "slug": "basketball",
    "title": "Indoor/Outdoor Composite Leather Basketball (Size 7)",
    "price": 39.00,
    "strikePrice": 69.00,
    "discount": "43% OFF",
    "category": "sports",
    "subCategory": "Team Sports",
    "subCategorySlug": "team-sports",
    "image": "🏀",
    "rating": 4.5,
    "inStock": true,
    "stockQuantity": 140,
    "sku": "SPORT-BB-037",
    "shortDescription": "Official size 7 basketball with a composite leather cover for superior grip and durability on any court.",
    "longDescription": "The high-quality **composite leather cover** provides the soft feel and grip of an indoor ball with the durability needed for outdoor courts. Features deep channels for better handling and control.",
    "specifications": [
      { "key": "Size", "value": "Size 7 (Official)" },
      { "key": "Material", "value": "Composite Leather" },
      { "key": "Use", "value": "Indoor/Outdoor" },
      { "key": "Feature", "value": "Deep Channel Design" }
    ],
    "shippingAndReturns": { "shippingWeight": "0.6 kg", "deliveryTime": "3-6 Business Days", "returnPolicy": "14-Day Return Policy" },
    "warranty": { "duration": "N/A", "coverage": "N/A" }
  },
  {
    "id": "38",
    "slug": "tennis-racket",
    "title": "Lightweight Graphite Tennis Racket",
    "price": 89.00,
    "strikePrice": 149.00,
    "discount": "40% OFF",
    "category": "sports",
    "subCategory": "Racquet Sports",
    "subCategorySlug": "racquet-sports",
    "image": "🎾",
    "badge": "Popular",
    "rating": 4.6,
    "inStock": true,
    "stockQuantity": 100,
    "sku": "SPORT-TR-038",
    "shortDescription": "Mid-level tennis racket featuring a graphite composite frame for power and control. Comes pre-strung.",
    "longDescription": "Constructed with a **lightweight graphite composite**, this racket offers a blend of power, maneuverability, and comfort. The large sweet spot is forgiving for intermediate players. Pre-strung and ready to play.",
    "specifications": [
      { "key": "Construction", "value": "Graphite Composite" },
      { "key": "Head Size", "value": "Midplus (100 sq in)" },
      { "key": "Weight", "value": "280g (Unstrung)" },
      { "key": "Grip Size", "value": "Various Options" }
    ],
    "shippingAndReturns": { "shippingWeight": "0.4 kg", "deliveryTime": "3-7 Business Days", "returnPolicy": "30-Day Return Policy" },
    "warranty": { "duration": "N/A", "coverage": "N/A" }
  },
  {
    "id": "39",
    "slug": "swimming-goggles",
    "title": "Anti-Fog & UV Protection Swimming Goggles",
    "price": 25.00,
    "strikePrice": 39.00,
    "discount": "36% OFF",
    "category": "sports",
    "subCategory": "Swimming Gear",
    "subCategorySlug": "swimming-gear",
    "image": "🏊",
    "rating": 4.3,
    "inStock": true,
    "stockQuantity": 350,
    "sku": "SPORT-SG-039",
    "shortDescription": "Leak-proof swimming goggles with anti-fog coating and UV protection. Comfortable, adjustable silicone straps.",
    "longDescription": "Designed for clarity and comfort, these goggles feature lenses with **anti-fog and UV protection**. The silicone eye gasket creates a secure, leak-proof seal. Quick-adjust strap system makes fitting simple.",
    "specifications": [
      { "key": "Lens Material", "value": "Polycarbonate" },
      { "key": "Features", "value": "Anti-Fog, UV Protection" },
      { "key": "Gasket Material", "value": "Silicone (Leak-Proof)" },
      { "key": "Strap", "value": "Adjustable Silicone" }
    ],
    "shippingAndReturns": { "shippingWeight": "0.1 kg", "deliveryTime": "2-5 Business Days", "returnPolicy": "14-Day Return Policy" },
    "warranty": { "duration": "N/A", "coverage": "N/A" }
  },
  {
    "id": "40",
    "slug": "bicycle-helmet",
    "title": "Safety Bicycle Helmet with LED Light",
    "price": 49.00,
    "strikePrice": 89.00,
    "discount": "45% OFF",
    "category": "sports",
    "subCategory": "Cycling",
    "subCategorySlug": "cycling",
    "image": "🚴",
    "rating": 4.5,
    "inStock": true,
    "stockQuantity": 120,
    "sku": "SPORT-BH-040",
    "shortDescription": "Lightweight, CPSC certified cycling helmet with excellent ventilation and integrated rear LED safety light.",
    "longDescription": "Prioritize safety with this helmet featuring in-mold construction for durability and shock absorption. Includes **20 ventilation vents** for cooling and a dial-fit system for a secure, custom fit. The integrated **rechargeable rear LED** enhances visibility.",
    "specifications": [
      { "key": "Construction", "value": "In-Mold (PC Shell, EPS Liner)" },
      { "key": "Safety Certification", "value": "CPSC Certified" },
      { "key": "Features", "value": "Integrated LED Light, 20 Vents" },
      { "key": "Adjustment", "value": "Dial Fit System" }
    ],
    "shippingAndReturns": { "shippingWeight": "0.5 kg", "deliveryTime": "3-6 Business Days", "returnPolicy": "30-Day Return Policy" },
    "warranty": { "duration": "N/A", "coverage": "N/A" }
  },

  // ----------------------------------------------------------------------
  // Toys
  // ----------------------------------------------------------------------
  {
    "id": "41",
    "slug": "building-blocks",
    "title": "Creative Building Blocks Set - 500pc Educational Toy",
    "price": 69.00,
    "strikePrice": 119.00,
    "discount": "42% OFF",
    "category": "toys",
    "subCategory": "Construction Toys",
    "subCategorySlug": "construction-toys",
    "image": "🧱",
    "badge": "Best Seller",
    "rating": 4.8,
    "inStock": true,
    "stockQuantity": 180,
    "sku": "TOYS-BB-001",
    "shortDescription": "A massive 500-piece set of classic building blocks to stimulate creativity, fine motor skills, and problem-solving in children aged 4+.",
    "longDescription": "The Creative Building Blocks Set offers limitless possibilities for young builders. This large 500-piece kit includes blocks in **10 vibrant colors** and **5 different shapes/sizes**. Made from **BPA-free, non-toxic ABS plastic**, the blocks are safe and durable. Excellent for developing **STEM skills**.",
    "specifications": [
      { "key": "Total Pieces", "value": "500 Pieces" },
      { "key": "Material", "value": "BPA-Free ABS Plastic" },
      { "key": "Recommended Age", "value": "4 Years and Up" },
      { "key": "Colors Included", "value": "10 Assorted Colors" }
    ],
    "shippingAndReturns": { "shippingWeight": "2.5 kg", "deliveryTime": "3-6 Business Days", "returnPolicy": "30-Day hassle-free return for unopened sets." },
    "warranty": { "duration": "N/A", "coverage": "N/A" }
  },
  {
    "id": "42",
    "slug": "stuffed-bear",
    "title": "Giant Soft Stuffed Teddy Bear - 1 Meter Tall",
    "price": 59.00,
    "strikePrice": 99.00,
    "discount": "40% OFF",
    "category": "toys",
    "subCategory": "Stuffed Animals",
    "subCategorySlug": "stuffed-animals",
    "image": "🧸",
    "badge": "Popular",
    "rating": 4.7,
    "inStock": true,
    "stockQuantity": 110,
    "sku": "TOYS-TB-042",
    "shortDescription": "Huge, ultra-soft teddy bear, perfect for cuddling and a beloved gift for any occasion.",
    "longDescription": "This giant teddy bear is one meter tall and made from luxuriously soft, hypoallergenic plush material. Filled with resilient PP cotton stuffing to maintain its shape. It's safe for all ages and makes a fantastic bedroom decoration.",
    "specifications": [
      { "key": "Height", "value": "100 cm (1 Meter)" },
      { "key": "Material", "value": "Soft Hypoallergenic Plush" },
      { "key": "Stuffing", "value": "PP Cotton" },
      { "key": "Safety Rating", "value": "Non-Toxic, Suitable for All Ages" }
    ],
    "shippingAndReturns": { "shippingWeight": "3.0 kg (Compressed)", "deliveryTime": "4-7 Business Days", "returnPolicy": "30-Day Return Policy" },
    "warranty": { "duration": "N/A", "coverage": "N/A" }
  },
  {
    "id": "43",
    "slug": "rc-car",
    "title": "Remote Control Racing Car - High Speed Off-Road",
    "price": 89.00,
    "strikePrice": 149.00,
    "discount": "40% OFF",
    "category": "toys",
    "subCategory": "Remote Control",
    "subCategorySlug": "remote-control",
    "image": "🚗",
    "rating": 4.6,
    "inStock": true,
    "stockQuantity": 95,
    "sku": "TOYS-RC-043",
    "shortDescription": "1:18 scale high-speed RC truck for off-road fun. Durable construction and powerful motor.",
    "longDescription": "Experience thrilling off-road action with this durable Remote Control Car. Capable of speeds up to 20 km/h, it features oversized tires and a strong suspension system to handle rugged terrains. Includes a rechargeable battery and 2.4GHz controller.",
    "specifications": [
      { "key": "Scale", "value": "1:18" },
      { "key": "Max Speed", "value": "20 km/h" },
      { "key": "Battery", "value": "Rechargeable Lithium (Included)" },
      { "key": "Control Frequency", "value": "2.4 GHz" }
    ],
    "shippingAndReturns": { "shippingWeight": "1.5 kg", "deliveryTime": "3-6 Business Days", "returnPolicy": "30-Day Return Policy" },
    "warranty": { "duration": "3 Months Limited Warranty", "coverage": "Motor and Functionality" }
  },
  {
    "id": "44",
    "slug": "puzzle-set",
    "title": "Educational Puzzle Set - 3 in 1 (1000 Pieces)",
    "price": 35.00,
    "strikePrice": 59.00,
    "discount": "41% OFF",
    "category": "toys",
    "subCategory": "Puzzles & Games",
    "subCategorySlug": "puzzles-games",
    "image": "🧩",
    "rating": 4.5,
    "inStock": true,
    "stockQuantity": 220,
    "sku": "TOYS-PZ-044",
    "shortDescription": "Three 1000-piece puzzles in one box, featuring classic landscapes. Great for family fun and cognitive development.",
    "longDescription": "A value set offering three uniquely designed 1000-piece jigsaws. Made from premium recycled cardboard with precision-cut pieces that lock together perfectly. A challenging and rewarding activity for teens and adults.",
    "specifications": [
      { "key": "Quantity", "value": "3 Puzzles" },
      { "key": "Piece Count", "value": "1000 Pieces Each" },
      { "key": "Material", "value": "Recycled Cardboard" },
      { "key": "Finished Size", "value": "70cm x 50cm (Approx)" }
    ],
    "shippingAndReturns": { "shippingWeight": "1.0 kg", "deliveryTime": "3-6 Business Days", "returnPolicy": "14-Day Return Policy" },
    "warranty": { "duration": "N/A", "coverage": "N/A" }
  },
  {
    "id": "45",
    "slug": "toy-robot",
    "title": "Interactive STEM Coding Robot Toy",
    "price": 99.00,
    "strikePrice": 169.00,
    "discount": "41% OFF",
    "category": "toys",
    "subCategory": "Educational Toys",
    "subCategorySlug": "educational-toys",
    "image": "🤖",
    "badge": "New Arrival",
    "rating": 4.6,
    "inStock": true,
    "stockQuantity": 70,
    "sku": "TOYS-RO-045",
    "shortDescription": "Programmable robot toy introducing kids to basic coding and engineering concepts through fun interactions.",
    "longDescription": "This toy robot makes learning fun by teaching children basic **block-based coding** concepts. It features sound effects, lights, and sensors to interact with its environment. Ideal for children aged 8+ to foster **STEM education**.",
    "specifications": [
      { "key": "Function", "value": "Programmable, Interactive" },
      { "key": "Learning Focus", "value": "STEM, Basic Coding" },
      { "key": "Recommended Age", "value": "8 Years and Up" },
      { "key": "Power Source", "value": "AAA Batteries (Not Included)" }
    ],
    "shippingAndReturns": { "shippingWeight": "1.0 kg", "deliveryTime": "3-6 Business Days", "returnPolicy": "30-Day Return Policy" },
    "warranty": { "duration": "6 Months Limited Warranty", "coverage": "Functionality" }
  },
  {
    "id": "46",
    "slug": "play-kitchen",
    "title": "Kids Wooden Play Kitchen Set",
    "price": 129.00,
    "strikePrice": 219.00,
    "discount": "41% OFF",
    "category": "toys",
    "subCategory": "Role Play",
    "subCategorySlug": "role-play",
    "image": "🍽️",
    "rating": 4.7,
    "inStock": true,
    "stockQuantity": 60,
    "sku": "TOYS-PK-046",
    "shortDescription": "Large, durable wooden play kitchen featuring a sink, oven, and interactive knobs. Promotes imaginative play.",
    "longDescription": "This beautifully crafted wooden kitchen provides hours of imaginative play. Features realistic accessories like clicking knobs, a removable sink for easy cleaning, and ample storage. Made from non-toxic, child-safe paint.",
    "specifications": [
      { "key": "Material", "value": "Wood, Non-Toxic Paint" },
      { "key": "Features", "value": "Clicking Knobs, Sink, Oven, Storage" },
      { "key": "Recommended Age", "value": "3 Years and Up" },
      { "key": "Assembly", "value": "Required (Instructions Included)" }
    ],
    "shippingAndReturns": { "shippingWeight": "15.0 kg", "deliveryTime": "5-10 Business Days", "returnPolicy": "30-Day Return Policy" },
    "warranty": { "duration": "N/A", "coverage": "N/A" }
  },
  {
    "id": "47",
    "slug": "toy-train",
    "title": "Electric Train Set with Tracks and Sound",
    "price": 79.00,
    "strikePrice": 129.00,
    "discount": "39% OFF",
    "category": "toys",
    "subCategory": "Vehicles",
    "subCategorySlug": "vehicles",
    "image": "🚂",
    "rating": 4.5,
    "inStock": true,
    "stockQuantity": 100,
    "sku": "TOYS-TR-047",
    "shortDescription": "Classic electric train set featuring a locomotive, cargo cars, and a complete oval track layout with realistic sound effects.",
    "longDescription": "A great starter train set! The locomotive features working lights and realistic steam sounds. Easy-to-assemble track creates a 1.2-meter oval layout. Develops creativity and fine motor skills in young children.",
    "specifications": [
      { "key": "Pieces", "value": "20+ (Train, Cars, Track)" },
      { "key": "Features", "value": "Working Headlight, Realistic Sound" },
      { "key": "Track Layout", "value": "Oval (1.2m diameter)" },
      { "key": "Power Source", "value": "AA Batteries (Not Included)" }
    ],
    "shippingAndReturns": { "shippingWeight": "1.8 kg", "deliveryTime": "3-6 Business Days", "returnPolicy": "30-Day Return Policy" },
    "warranty": { "duration": "N/A", "coverage": "N/A" }
  },
  {
    "id": "48",
    "slug": "art-set",
    "title": "Complete Art & Craft Set for Kids - 120pc",
    "price": 45.00,
    "strikePrice": 79.00,
    "discount": "43% OFF",
    "category": "toys",
    "subCategory": "Arts & Crafts",
    "subCategorySlug": "arts-crafts",
    "image": "🎨",
    "rating": 4.4,
    "inStock": true,
    "stockQuantity": 250,
    "sku": "TOYS-AS-048",
    "shortDescription": "120-piece deluxe art kit in a portable wooden case, including crayons, colored pencils, markers, and paint.",
    "longDescription": "Unleash creativity with this comprehensive art set. The high-quality wooden carrying case keeps all 120 supplies organized. Includes materials for drawing, coloring, and painting. Non-toxic and safe for children.",
    "specifications": [
      { "key": "Pieces", "value": "120 Pieces" },
      { "key": "Case Material", "value": "Wooden Carrying Case" },
      { "key": "Contents", "value": "Markers, Pencils, Crayons, Watercolors" },
      { "key": "Safety", "value": "Non-Toxic" }
    ],
    "shippingAndReturns": { "shippingWeight": "1.2 kg", "deliveryTime": "3-6 Business Days", "returnPolicy": "30-Day Return Policy" },
    "warranty": { "duration": "N/A", "coverage": "N/A" }
  },

  // ----------------------------------------------------------------------
  // Books
  // ----------------------------------------------------------------------
  {
    "id": "49",
    "slug": "fiction-bestseller",
    "title": "The Silent City: A Bestselling Mystery Novel",
    "price": 39.00,
    "strikePrice": 69.00,
    "discount": "43% OFF",
    "category": "books",
    "subCategory": "Fiction",
    "subCategorySlug": "fiction",
    "image": "📚",
    "badge": "Best Seller",
    "rating": 4.8,
    "inStock": true,
    "stockQuantity": 300,
    "sku": "BOOK-FN-001",
    "shortDescription": "A gripping international bestseller—a tale of suspense, mystery, and an ancient secret hidden within modern city walls.",
    "longDescription": "**'The Silent City'** is the debut novel by acclaimed author Elara Vance. It follows investigative journalist Clara as she unravels a 500-year-old conspiracy linked to a series of present-day disappearances. This is the **Hardcover Special Edition** featuring an exclusive author's note.",
    "specifications": [
      { "key": "Author", "value": "Elara Vance" },
      { "key": "Genre", "value": "Mystery, Thriller, Suspense" },
      { "key": "Format", "value": "Hardcover" },
      { "key": "Page Count", "value": "416 Pages" },
      { "key": "ISBN", "value": "978-1234567890" }
    ],
    "shippingAndReturns": { "shippingWeight": "0.6 kg", "deliveryTime": "2-4 Business Days", "returnPolicy": "Returns accepted if item is undamaged within 14 days." },
    "warranty": { "duration": "N/A", "coverage": "N/A" }
  },
  {
    "id": "50",
    "slug": "self-help-book",
    "title": "Personal Development Book Set - Achieve Your Best",
    "price": 49.00,
    "strikePrice": 89.00,
    "discount": "45% OFF",
    "category": "books",
    "subCategory": "Non-Fiction",
    "subCategorySlug": "non-fiction",
    "image": "📖",
    "rating": 4.7,
    "inStock": true,
    "stockQuantity": 250,
    "sku": "BOOK-SH-050",
    "shortDescription": "A 3-book set focusing on productivity, mindset, and financial freedom. Practical advice for personal growth.",
    "longDescription": "This curated set includes three top-rated self-help books designed to guide you toward achieving your personal and professional goals. Topics include habit building, overcoming procrastination, and basic financial literacy.",
    "specifications": [
      { "key": "Genre", "value": "Self-Help, Personal Development" },
      { "key": "Format", "value": "Paperback" },
      { "key": "Set Count", "value": "3 Books" },
      { "key": "Language", "value": "English" }
    ],
    "shippingAndReturns": { "shippingWeight": "1.0 kg", "deliveryTime": "2-4 Business Days", "returnPolicy": "14-Day Return Policy" },
    "warranty": { "duration": "N/A", "coverage": "N/A" }
  },
  {
    "id": "51",
    "slug": "cookbook",
    "title": "Complete Cooking Guide - 500 Recipes for Home Chefs",
    "price": 45.00,
    "strikePrice": 79.00,
    "discount": "43% OFF",
    "category": "books",
    "subCategory": "Non-Fiction",
    "subCategorySlug": "non-fiction",
    "image": "🍳",
    "rating": 4.6,
    "inStock": true,
    "stockQuantity": 180,
    "sku": "BOOK-CK-051",
    "shortDescription": "An all-in-one cookbook featuring 500 easy-to-follow recipes from global cuisines, complete with step-by-step photos.",
    "longDescription": "From beginner basics to advanced techniques, this comprehensive guide covers everything from weeknight dinners to holiday feasts. Includes sections on essential techniques, ingredient guides, and meal planning.",
    "specifications": [
      { "key": "Genre", "value": "Cooking, Culinary Arts" },
      { "key": "Format", "value": "Hardcover" },
      { "key": "Recipe Count", "value": "500+" },
      { "key": "Feature", "value": "Color Photography" }
    ],
    "shippingAndReturns": { "shippingWeight": "1.2 kg", "deliveryTime": "3-5 Business Days", "returnPolicy": "14-Day Return Policy" },
    "warranty": { "duration": "N/A", "coverage": "N/A" }
  },
  {
    "id": "52",
    "slug": "childrens-books",
    "title": "Children's Story Book Collection - 10 Books",
    "price": 35.00,
    "strikePrice": 59.00,
    "discount": "41% OFF",
    "category": "books",
    "subCategory": "Children's Books",
    "subCategorySlug": "childrens-books",
    "image": "📕",
    "badge": "Popular",
    "rating": 4.7,
    "inStock": true,
    "stockQuantity": 400,
    "sku": "BOOK-CB-052",
    "shortDescription": "A charming 10-book collection of illustrated bedtime stories designed for early readers (Ages 3-7).",
    "longDescription": "Inspire a love of reading with this delightful collection. Each book features vibrant illustrations and simple, engaging stories that teach valuable lessons about friendship, sharing, and imagination. Durable hardcover design.",
    "specifications": [
      { "key": "Genre", "value": "Children's Picture Books" },
      { "key": "Format", "value": "Hardcover" },
      { "key": "Set Count", "value": "10 Books" },
      { "key": "Age Range", "value": "3-7 Years" }
    ],
    "shippingAndReturns": { "shippingWeight": "1.5 kg", "deliveryTime": "3-5 Business Days", "returnPolicy": "30-Day Return Policy" },
    "warranty": { "duration": "N/A", "coverage": "N/A" }
  },
  {
    "id": "53",
    "slug": "science-book",
    "title": "Science & Technology Encyclopedia (2025 Edition)",
    "price": 59.00,
    "strikePrice": 99.00,
    "discount": "40% OFF",
    "category": "books",
    "subCategory": "Non-Fiction",
    "subCategorySlug": "non-fiction",
    "image": "🔬",
    "rating": 4.5,
    "inStock": true,
    "stockQuantity": 120,
    "sku": "BOOK-SC-053",
    "shortDescription": "A comprehensive, up-to-date encyclopedia covering physics, biology, space, and modern technology.",
    "longDescription": "An invaluable reference book for students and enthusiasts. Features thousands of definitions, detailed diagrams, and in-depth articles on major scientific breakthroughs and technological innovations. Hardcover collector's edition.",
    "specifications": [
      { "key": "Genre", "value": "Reference, Science" },
      { "key": "Format", "value": "Hardcover" },
      { "key": "Feature", "value": "Full-Color Illustrations" },
      { "key": "Target Audience", "value": "Students, Enthusiasts" }
    ],
    "shippingAndReturns": { "shippingWeight": "2.0 kg", "deliveryTime": "4-7 Business Days", "returnPolicy": "14-Day Return Policy" },
    "warranty": { "duration": "N/A", "coverage": "N/A" }
  },
  {
    "id": "54",
    "slug": "history-book",
    "title": "World History Complete Collection (Abridged)",
    "price": 69.00,
    "strikePrice": 119.00,
    "discount": "42% OFF",
    "category": "books",
    "subCategory": "Non-Fiction",
    "subCategorySlug": "non-fiction",
    "image": "📜",
    "rating": 4.6,
    "inStock": true,
    "stockQuantity": 150,
    "sku": "BOOK-HI-054",
    "shortDescription": "A narrative journey through major global events from ancient civilizations to the modern era, abridged for general readers.",
    "longDescription": "This accessible history book offers a chronological overview of world history, highlighting key cultural, political, and social developments. Includes maps, timelines, and compelling analysis. Essential reading for history buffs.",
    "specifications": [
      { "key": "Genre", "value": "History, Reference" },
      { "key": "Format", "value": "Paperback" },
      { "key": "Feature", "value": "Maps and Timelines" },
      { "key": "Period Covered", "value": "Ancient to Modern" }
    ],
    "shippingAndReturns": { "shippingWeight": "1.1 kg", "deliveryTime": "3-6 Business Days", "returnPolicy": "14-Day Return Policy" },
    "warranty": { "duration": "N/A", "coverage": "N/A" }
  },
  {
    "id": "55",
    "slug": "biography",
    "title": "Inspiring Biography Collection - Innovators Series",
    "price": 39.00,
    "strikePrice": 69.00,
    "discount": "43% OFF",
    "category": "books",
    "subCategory": "Non-Fiction",
    "subCategorySlug": "non-fiction",
    "image": "📰",
    "rating": 4.5,
    "inStock": true,
    "stockQuantity": 180,
    "sku": "BOOK-BI-055",
    "shortDescription": "A collection of 4 short biographies focusing on the lives of famous scientists, artists, and business innovators.",
    "longDescription": "Dive into the lives of some of history's most creative and influential figures. This set provides an engaging look at their challenges, breakthroughs, and legacies. Great for motivation and learning.",
    "specifications": [
      { "key": "Genre", "value": "Biography, Memoir" },
      { "key": "Format", "value": "Paperback" },
      { "key": "Set Count", "value": "4 Biographies" },
      { "key": "Series", "value": "Innovators Series" }
    ],
    "shippingAndReturns": { "shippingWeight": "0.9 kg", "deliveryTime": "2-5 Business Days", "returnPolicy": "14-Day Return Policy" },
    "warranty": { "duration": "N/A", "coverage": "N/A" }
  },
  {
    "id": "56",
    "slug": "comic-books",
    "title": "Superhero Comic Book Bundle - 5 Issues",
    "price": 49.00,
    "strikePrice": 89.00,
    "discount": "45% OFF",
    "category": "books",
    "subCategory": "Comics & Graphic Novels",
    "subCategorySlug": "comics-graphic-novels",
    "image": "💥",
    "badge": "Hot Deal",
    "rating": 4.8,
    "inStock": true,
    "stockQuantity": 100,
    "sku": "BOOK-CM-056",
    "shortDescription": "A bundle of 5 high-action superhero comic issues featuring exclusive variant covers.",
    "longDescription": "Perfect for collectors and new readers. This bundle contains five consecutive issues from the critically acclaimed 'Cosmic Vanguard' series. Features high-quality printing and exclusive cover art unavailable anywhere else.",
    "specifications": [
      { "key": "Genre", "value": "Superhero, Comics" },
      { "key": "Format", "value": "Softcover Issues" },
      { "key": "Bundle Count", "value": "5 Issues" },
      { "key": "Feature", "value": "Exclusive Variant Covers" }
    ],
    "shippingAndReturns": { "shippingWeight": "0.3 kg", "deliveryTime": "2-5 Business Days", "returnPolicy": "Returns accepted only if complete set is sealed." },
    "warranty": { "duration": "N/A", "coverage": "N/A" }
  },

  // ----------------------------------------------------------------------
  // Gaming
  // ----------------------------------------------------------------------
  {
    "id": "57",
    "slug": "gaming-controller",
    "title": "Wireless Gaming Controller Pro for PC & Console",
    "price": 79.00,
    "strikePrice": 129.00,
    "discount": "39% OFF",
    "category": "gaming",
    "subCategory": "Accessories",
    "subCategorySlug": "accessories-gaming",
    "image": "🎮",
    "badge": "Best Seller",
    "rating": 4.7,
    "inStock": true,
    "stockQuantity": 160,
    "sku": "GAMING-CON-057",
    "shortDescription": "High-precision wireless controller with trigger stops, programmable back paddles, and ergonomic grip.",
    "longDescription": "Built for competitive play. Features ultra-responsive buttons, adjustable **hair trigger locks**, and two **mappable back paddles** for quick actions. Compatible with PC, Android, and major consoles via USB dongle or Bluetooth.",
    "specifications": [
      { "key": "Connection", "value": "Wireless (2.4GHz Dongle/Bluetooth)" },
      { "key": "Feature", "value": "Programmable Paddles, Trigger Stops" },
      { "key": "Compatibility", "value": "PC, Android, Console" },
      { "key": "Battery", "value": "Rechargeable (20 hours playtime)" }
    ],
    "shippingAndReturns": { "shippingWeight": "0.4 kg", "deliveryTime": "2-4 Business Days", "returnPolicy": "30-Day Return Policy" },
    "warranty": { "duration": "1 Year Limited Warranty", "coverage": "Buttons and Stick Drift" }
  },
  {
    "id": "58",
    "slug": "gaming-headset",
    "title": "7.1 Surround Sound Gaming Headset",
    "price": 129.00,
    "strikePrice": 219.00,
    "discount": "41% OFF",
    "category": "gaming",
    "subCategory": "Audio",
    "subCategorySlug": "audio-gaming",
    "image": "🎧",
    "badge": "Popular",
    "rating": 4.8,
    "inStock": true,
    "stockQuantity": 130,
    "sku": "GAMING-HS-058",
    "shortDescription": "Immersive 7.1 virtual surround sound, cooling gel ear cushions, and a clear, retractable noise-canceling mic.",
    "longDescription": "Pinpoint enemy location with crystal-clear **7.1 virtual surround sound** audio. Features large 50mm drivers and lightweight aluminum frame construction. The memory foam cushions are infused with **cooling gel** for marathon gaming sessions.",
    "specifications": [
      { "key": "Sound", "value": "7.1 Virtual Surround" },
      { "key": "Driver Size", "value": "50mm" },
      { "key": "Microphone", "value": "Retractable Noise-Canceling" },
      { "key": "Ear Cushions", "value": "Cooling Gel Infused" }
    ],
    "shippingAndReturns": { "shippingWeight": "0.6 kg", "deliveryTime": "2-5 Business Days", "returnPolicy": "30-Day Return Policy" },
    "warranty": { "duration": "2 Years Limited Warranty", "coverage": "Audio Drivers" }
  },
  {
    "id": "59",
    "slug": "gaming-chair",
    "title": "Ergonomic High-Back Gaming Chair with RGB",
    "price": 299.00,
    "strikePrice": 499.00,
    "discount": "40% OFF",
    "category": "gaming",
    "subCategory": "Furniture",
    "subCategorySlug": "furniture-gaming",
    "image": "🪑",
    "badge": "Premium",
    "rating": 4.6,
    "inStock": true,
    "stockQuantity": 50,
    "sku": "GAMING-CH-059",
    "shortDescription": "Premium PU leather gaming chair with adjustable lumbar support, 4D armrests, and customizable RGB lighting strips.",
    "longDescription": "Built for comfort during long gaming marathons. Features a high-density molded foam seat, adjustable lumbar and neck pillows, and a reclining back up to 150 degrees. The integrated **RGB lighting** is controlled via remote.",
    "specifications": [
      { "key": "Material", "value": "PU Faux Leather, Steel Frame" },
      { "key": "Recline Angle", "value": "Up to 150 Degrees" },
      { "key": "Features", "value": "4D Armrests, Lumbar/Neck Pillows, RGB Lighting" },
      { "key": "Weight Capacity", "value": "136 kg (300 lbs)" }
    ],
    "shippingAndReturns": { "shippingWeight": "25.0 kg", "deliveryTime": "5-10 Business Days", "returnPolicy": "30-Day Return Policy" },
    "warranty": { "duration": "3 Years Limited Warranty", "coverage": "Frame and Base" }
  },
  {
    "id": "60",
    "slug": "gaming-mouse-pad",
    "title": "XXL RGB Gaming Mouse Pad (Desk Mat)",
    "price": 39.00,
    "strikePrice": 69.00,
    "discount": "43% OFF",
    "category": "gaming",
    "subCategory": "Accessories",
    "subCategorySlug": "accessories-gaming",
    "image": "🖱️",
    "rating": 4.5,
    "inStock": true,
    "stockQuantity": 220,
    "sku": "GAMING-MP-060",
    "shortDescription": "Extra-large desk mat with a smooth surface for speed and precision, framed by customizable RGB lighting.",
    "longDescription": "Cover your entire desk with this extra-large mouse pad. Features a micro-woven fabric surface optimized for both speed and control. The thick, non-slip rubber base keeps it firmly in place. Choose from 14 lighting modes for the border RGB.",
    "specifications": [
      { "key": "Size", "value": "XXL (900 x 400 mm)" },
      { "key": "Surface", "value": "Micro-Woven Fabric (Speed/Control)" },
      { "key": "Base", "value": "Non-Slip Rubber" },
      { "key": "Feature", "value": "14 Mode RGB Lighting" }
    ],
    "shippingAndReturns": { "shippingWeight": "0.8 kg", "deliveryTime": "3-6 Business Days", "returnPolicy": "30-Day Return Policy" },
    "warranty": { "duration": "N/A", "coverage": "N/A" }
  },
  {
    "id": "61",
    "slug": "vr-headset",
    "title": "Virtual Reality VR Headset - All-in-One",
    "price": 349.00,
    "strikePrice": 599.00,
    "discount": "42% OFF",
    "category": "gaming",
    "subCategory": "Virtual Reality",
    "subCategorySlug": "virtual-reality",
    "image": "🥽",
    "badge": "New Arrival",
    "rating": 4.7,
    "inStock": true,
    "stockQuantity": 80,
    "sku": "GAMING-VR-061",
    "shortDescription": "Standalone VR headset offering a seamless, wire-free virtual reality experience with high-resolution display and hand tracking.",
    "longDescription": "Step into immersive worlds with this all-in-one VR system. No PC or console required. Features a crisp, high-resolution screen, built-in spatial audio, and accurate six-degrees-of-freedom (6DOF) tracking. Includes two touch controllers.",
    "specifications": [
      { "key": "Type", "value": "Standalone VR System" },
      { "key": "Resolution", "value": "High Resolution Per Eye" },
      { "key": "Tracking", "value": "6DOF Head and Hand Tracking" },
      { "key": "Feature", "value": "Built-in Audio, 128GB Storage" }
    ],
    "shippingAndReturns": { "shippingWeight": "1.5 kg", "deliveryTime": "3-7 Business Days", "returnPolicy": "30-Day Return Policy" },
    "warranty": { "duration": "1 Year Limited Warranty", "coverage": "Hardware" }
  },
  {
    "id": "62",
    "slug": "gaming-monitor",
    "title": "27\" 144Hz WQHD Gaming Monitor with 1ms Response Time",
    "price": 399.00,
    "strikePrice": 699.00,
    "discount": "43% OFF",
    "category": "gaming",
    "subCategory": "Displays",
    "subCategorySlug": "displays-gaming",
    "image": "🖥️",
    "badge": "Hot Deal",
    "rating": 4.8,
    "inStock": true,
    "stockQuantity": 70,
    "sku": "GAMING-MON-062",
    "shortDescription": "27-inch WQHD (2560x1440) monitor with a blazing fast 144Hz refresh rate and 1ms response time for competitive gaming.",
    "longDescription": "Gain the competitive edge with this high-performance 27-inch gaming monitor. The **144Hz refresh rate** and **1ms response time** virtually eliminate motion blur. Supports **Adaptive Sync** technology and includes **adjustable height and pivot** for ergonomic setup.",
    "specifications": [
      { "key": "Screen Size", "value": "27 Inches" },
      { "key": "Resolution", "value": "WQHD (2560 x 1440)" },
      { "key": "Refresh Rate", "value": "144 Hz" },
      { "key": "Response Time", "value": "1ms (MPRT)" }
    ],
    "shippingAndReturns": { "shippingWeight": "8.5 kg", "deliveryTime": "4-7 Business Days", "returnPolicy": "30-Day dead pixel and defect warranty." },
    "warranty": { "duration": "3 Years Parts and Labor Warranty", "coverage": "All non-user-caused defects" }
  },
  {
    "id": "63",
    "slug": "capture-card",
    "title": "4K Ultra HD Capture Card for Streaming",
    "price": 179.00,
    "strikePrice": 299.00,
    "discount": "40% OFF",
    "category": "gaming",
    "subCategory": "Streaming Gear",
    "subCategorySlug": "streaming-gear",
    "image": "📹",
    "rating": 4.6,
    "inStock": true,
    "stockQuantity": 90,
    "sku": "GAMING-CC-063",
    "shortDescription": "Professional external capture card supporting 4K passthrough and 1080p 60fps recording/streaming with near-zero latency.",
    "longDescription": "Essential gear for serious content creators. This external capture card handles **4K HDR passthrough** while allowing you to stream in high-quality **1080p at 60fps**. Plug-and-play USB 3.0 interface ensures minimal latency and easy setup across PC and console platforms.",
    "specifications": [
      { "key": "Resolution", "value": "1080p @ 60fps (Capture)" },
      { "key": "Passthrough", "value": "4K HDR" },
      { "key": "Interface", "value": "USB 3.0 (External)" },
      { "key": "Compatibility", "value": "PC, Mac, PS5, Xbox Series X" }
    ],
    "shippingAndReturns": { "shippingWeight": "0.2 kg", "deliveryTime": "2-4 Business Days", "returnPolicy": "30-Day Return Policy" },
    "warranty": { "duration": "1 Year Limited Warranty", "coverage": "Hardware" }
  },
  {
    "id": "64",
    "slug": "gaming-desk",
    "title": "Ergonomic Z-Shaped Gaming Desk with Pro Cable Management System",
    "price": 249.00,
    "strikePrice": 419.00,
    "discount": "41% OFF",
    "category": "gaming",
    "subCategory": "Furniture",
    "subCategorySlug": "furniture-gaming",
    "image": "🎯",
    "rating": 4.5,
    "inStock": true,
    "stockQuantity": 85,
    "sku": "GAMING-GD-064",
    "shortDescription": "Sturdy Z-shaped desk with carbon fiber texture, integrated cable management, cup holder, and headphone hook.",
    "longDescription": "This gaming desk is designed with an ergonomic Z-shape and a durable carbon fiber texture surface that is scratch-resistant. The integrated **cable management grommets and tray** keep your setup clean. Features include a cup holder and headphone hook.",
    "specifications": [
      { "key": "Desk Shape", "value": "Z-Shape" },
      { "key": "Material", "value": "MDF Board with Carbon Fiber Texture, Steel Frame" },
      { "key": "Dimensions", "value": "120cm x 60cm x 75cm" },
      { "key": "Feature", "value": "Cable Management, Cup Holder, Headphone Hook" }
    ],
    "shippingAndReturns": { "shippingWeight": "25.0 kg", "deliveryTime": "5-10 Business Days", "returnPolicy": "30-Day Return Policy" },
    "warranty": { "duration": "1 Year Structural Warranty", "coverage": "Frame and Welds" }
  }
]
