import { Product, Category } from "@/types/product";

export const categories: Category[] = [
  { id: "1", name: "Electronics", slug: "electronics", icon: "📱" },
  { id: "2", name: "Fashion", slug: "fashion", icon: "👕" },
  { id: "3", name: "Home & Kitchen", slug: "home-kitchen", icon: "🏠" },
  { id: "4", name: "Beauty", slug: "beauty", icon: "💄" },
  { id: "5", name: "Sports", slug: "sports", icon: "⚽" },
  { id: "6", name: "Toys", slug: "toys", icon: "🧸" },
  { id: "7", name: "Books", slug: "books", icon: "📚" },
  { id: "8", name: "Gaming", slug: "gaming", icon: "🎮" },
];

export const products: Product[] = [
  // Electronics
  {
    id: "1",
    slug: "wireless-headphones",
    title: "Premium Wireless Headphones with Noise Cancellation",
    price: 299,
    strikePrice: 499,
    discount: "40% OFF",
    category: "electronics",
    image: "🎧",
    badge: "Best Seller",
    rating: 4.5,
    inStock: true,
  },
  {
    id: "2",
    slug: "smart-watch",
    title: "Smart Watch with Health Tracking",
    price: 199,
    strikePrice: 349,
    discount: "43% OFF",
    category: "electronics",
    image: "⌚",
    badge: "New Arrival",
    rating: 4.3,
    inStock: true,
  },
  {
    id: "3",
    slug: "bluetooth-speaker",
    title: "Portable Bluetooth Speaker - Waterproof",
    price: 89,
    strikePrice: 149,
    discount: "40% OFF",
    category: "electronics",
    image: "🔊",
    rating: 4.6,
    inStock: true,
  },
  {
    id: "4",
    slug: "wireless-mouse",
    title: "Ergonomic Wireless Mouse",
    price: 45,
    strikePrice: 79,
    discount: "43% OFF",
    category: "electronics",
    image: "🖱️",
    rating: 4.4,
    inStock: true,
  },
  {
    id: "5",
    slug: "mechanical-keyboard",
    title: "RGB Mechanical Gaming Keyboard",
    price: 129,
    strikePrice: 199,
    discount: "35% OFF",
    category: "electronics",
    image: "⌨️",
    badge: "Hot Deal",
    rating: 4.7,
    inStock: true,
  },
  {
    id: "6",
    slug: "laptop-stand",
    title: "Adjustable Aluminum Laptop Stand",
    price: 39,
    strikePrice: 69,
    discount: "43% OFF",
    category: "electronics",
    image: "💻",
    rating: 4.5,
    inStock: true,
  },
  {
    id: "7",
    slug: "usb-hub",
    title: "7-Port USB 3.0 Hub with Power Adapter",
    price: 29,
    strikePrice: 49,
    discount: "41% OFF",
    category: "electronics",
    image: "🔌",
    rating: 4.2,
    inStock: true,
  },
  {
    id: "8",
    slug: "webcam-hd",
    title: "1080p HD Webcam with Microphone",
    price: 79,
    strikePrice: 129,
    discount: "39% OFF",
    category: "electronics",
    image: "📷",
    rating: 4.3,
    inStock: true,
  },

  // Fashion
  {
    id: "9",
    slug: "cotton-t-shirt",
    title: "Premium Cotton T-Shirt - Pack of 3",
    price: 59,
    strikePrice: 99,
    discount: "40% OFF",
    category: "fashion",
    image: "👕",
    badge: "Popular",
    rating: 4.4,
    inStock: true,
  },
  {
    id: "10",
    slug: "denim-jeans",
    title: "Slim Fit Denim Jeans",
    price: 79,
    strikePrice: 129,
    discount: "39% OFF",
    category: "fashion",
    image: "👖",
    rating: 4.5,
    inStock: true,
  },
  {
    id: "11",
    slug: "leather-jacket",
    title: "Genuine Leather Jacket",
    price: 249,
    strikePrice: 399,
    discount: "38% OFF",
    category: "fashion",
    image: "🧥",
    badge: "Premium",
    rating: 4.8,
    inStock: true,
  },
  {
    id: "12",
    slug: "running-shoes",
    title: "Professional Running Shoes",
    price: 129,
    strikePrice: 199,
    discount: "35% OFF",
    category: "fashion",
    image: "👟",
    badge: "Best Seller",
    rating: 4.6,
    inStock: true,
  },
  {
    id: "13",
    slug: "casual-sneakers",
    title: "Comfortable Casual Sneakers",
    price: 89,
    strikePrice: 149,
    discount: "40% OFF",
    category: "fashion",
    image: "👞",
    rating: 4.4,
    inStock: true,
  },
  {
    id: "14",
    slug: "sports-cap",
    title: "Adjustable Sports Cap",
    price: 25,
    strikePrice: 39,
    discount: "36% OFF",
    category: "fashion",
    image: "🧢",
    rating: 4.2,
    inStock: true,
  },
  {
    id: "15",
    slug: "backpack",
    title: "Water Resistant Travel Backpack",
    price: 69,
    strikePrice: 119,
    discount: "42% OFF",
    category: "fashion",
    image: "🎒",
    rating: 4.7,
    inStock: true,
  },
  {
    id: "16",
    slug: "sunglasses",
    title: "Polarized UV Protection Sunglasses",
    price: 49,
    strikePrice: 89,
    discount: "45% OFF",
    category: "fashion",
    image: "🕶️",
    badge: "Hot Deal",
    rating: 4.5,
    inStock: true,
  },

  // Home & Kitchen
  {
    id: "17",
    slug: "coffee-maker",
    title: "Automatic Coffee Maker Machine",
    price: 159,
    strikePrice: 249,
    discount: "36% OFF",
    category: "home-kitchen",
    image: "☕",
    badge: "Best Seller",
    rating: 4.6,
    inStock: true,
  },
  {
    id: "18",
    slug: "blender",
    title: "High-Speed Blender 1200W",
    price: 119,
    strikePrice: 199,
    discount: "40% OFF",
    category: "home-kitchen",
    image: "🥤",
    rating: 4.5,
    inStock: true,
  },
  {
    id: "19",
    slug: "cookware-set",
    title: "Non-Stick Cookware Set - 10 Pieces",
    price: 179,
    strikePrice: 299,
    discount: "40% OFF",
    category: "home-kitchen",
    image: "🍳",
    badge: "Popular",
    rating: 4.7,
    inStock: true,
  },
  {
    id: "20",
    slug: "vacuum-cleaner",
    title: "Cordless Vacuum Cleaner",
    price: 229,
    strikePrice: 379,
    discount: "40% OFF",
    category: "home-kitchen",
    image: "🧹",
    badge: "New Arrival",
    rating: 4.6,
    inStock: true,
  },
  {
    id: "21",
    slug: "air-fryer",
    title: "Digital Air Fryer 5.5L",
    price: 149,
    strikePrice: 249,
    discount: "40% OFF",
    category: "home-kitchen",
    image: "🍟",
    badge: "Hot Deal",
    rating: 4.8,
    inStock: true,
  },
  {
    id: "22",
    slug: "knife-set",
    title: "Professional Chef Knife Set",
    price: 89,
    strikePrice: 149,
    discount: "40% OFF",
    category: "home-kitchen",
    image: "🔪",
    rating: 4.5,
    inStock: true,
  },
  {
    id: "23",
    slug: "cutting-board",
    title: "Bamboo Cutting Board Set",
    price: 35,
    strikePrice: 59,
    discount: "41% OFF",
    category: "home-kitchen",
    image: "🪵",
    rating: 4.4,
    inStock: true,
  },
  {
    id: "24",
    slug: "food-storage",
    title: "Glass Food Storage Containers - 12pc",
    price: 59,
    strikePrice: 99,
    discount: "40% OFF",
    category: "home-kitchen",
    image: "🥫",
    rating: 4.6,
    inStock: true,
  },

  // Beauty
  {
    id: "25",
    slug: "skincare-set",
    title: "Complete Skincare Set - 5 Products",
    price: 129,
    strikePrice: 219,
    discount: "41% OFF",
    category: "beauty",
    image: "💆",
    badge: "Best Seller",
    rating: 4.7,
    inStock: true,
  },
  {
    id: "26",
    slug: "makeup-brush-set",
    title: "Professional Makeup Brush Set - 12pc",
    price: 49,
    strikePrice: 89,
    discount: "45% OFF",
    category: "beauty",
    image: "💄",
    rating: 4.5,
    inStock: true,
  },
  {
    id: "27",
    slug: "hair-dryer",
    title: "Ionic Hair Dryer with Diffuser",
    price: 89,
    strikePrice: 149,
    discount: "40% OFF",
    category: "beauty",
    image: "💇",
    badge: "Popular",
    rating: 4.6,
    inStock: true,
  },
  {
    id: "28",
    slug: "perfume-set",
    title: "Luxury Perfume Gift Set",
    price: 179,
    strikePrice: 299,
    discount: "40% OFF",
    category: "beauty",
    image: "🌸",
    badge: "Premium",
    rating: 4.8,
    inStock: true,
  },
  {
    id: "29",
    slug: "face-mask-set",
    title: "Hydrating Face Mask Set - 10pc",
    price: 39,
    strikePrice: 69,
    discount: "43% OFF",
    category: "beauty",
    image: "🧖",
    rating: 4.4,
    inStock: true,
  },
  {
    id: "30",
    slug: "nail-polish-set",
    title: "Long-Lasting Nail Polish Set - 8 Colors",
    price: 45,
    strikePrice: 79,
    discount: "43% OFF",
    category: "beauty",
    image: "💅",
    rating: 4.3,
    inStock: true,
  },
  {
    id: "31",
    slug: "electric-shaver",
    title: "Rechargeable Electric Shaver",
    price: 99,
    strikePrice: 169,
    discount: "41% OFF",
    category: "beauty",
    image: "🪒",
    rating: 4.5,
    inStock: true,
  },
  {
    id: "32",
    slug: "makeup-mirror",
    title: "LED Makeup Mirror with 3X Magnification",
    price: 59,
    strikePrice: 99,
    discount: "40% OFF",
    category: "beauty",
    image: "🪞",
    rating: 4.6,
    inStock: true,
  },

  // Sports
  {
    id: "33",
    slug: "yoga-mat",
    title: "Premium Non-Slip Yoga Mat",
    price: 39,
    strikePrice: 69,
    discount: "43% OFF",
    category: "sports",
    image: "🧘",
    badge: "Best Seller",
    rating: 4.7,
    inStock: true,
  },
  {
    id: "34",
    slug: "dumbbell-set",
    title: "Adjustable Dumbbell Set - 20kg",
    price: 119,
    strikePrice: 199,
    discount: "40% OFF",
    category: "sports",
    image: "🏋️",
    rating: 4.6,
    inStock: true,
  },
  {
    id: "35",
    slug: "resistance-bands",
    title: "Resistance Bands Set - 5 Levels",
    price: 29,
    strikePrice: 49,
    discount: "41% OFF",
    category: "sports",
    image: "🎯",
    rating: 4.5,
    inStock: true,
  },
  {
    id: "36",
    slug: "soccer-ball",
    title: "Professional Soccer Ball",
    price: 45,
    strikePrice: 79,
    discount: "43% OFF",
    category: "sports",
    image: "⚽",
    rating: 4.4,
    inStock: true,
  },
  {
    id: "37",
    slug: "basketball",
    title: "Indoor/Outdoor Basketball",
    price: 39,
    strikePrice: 69,
    discount: "43% OFF",
    category: "sports",
    image: "🏀",
    rating: 4.5,
    inStock: true,
  },
  {
    id: "38",
    slug: "tennis-racket",
    title: "Lightweight Tennis Racket",
    price: 89,
    strikePrice: 149,
    discount: "40% OFF",
    category: "sports",
    image: "🎾",
    badge: "Popular",
    rating: 4.6,
    inStock: true,
  },
  {
    id: "39",
    slug: "swimming-goggles",
    title: "Anti-Fog Swimming Goggles",
    price: 25,
    strikePrice: 39,
    discount: "36% OFF",
    category: "sports",
    image: "🏊",
    rating: 4.3,
    inStock: true,
  },
  {
    id: "40",
    slug: "bicycle-helmet",
    title: "Safety Bicycle Helmet",
    price: 49,
    strikePrice: 89,
    discount: "45% OFF",
    category: "sports",
    image: "🚴",
    rating: 4.5,
    inStock: true,
  },

  // Toys
  {
    id: "41",
    slug: "building-blocks",
    title: "Creative Building Blocks Set - 500pc",
    price: 69,
    strikePrice: 119,
    discount: "42% OFF",
    category: "toys",
    image: "🧱",
    badge: "Best Seller",
    rating: 4.8,
    inStock: true,
  },
  {
    id: "42",
    slug: "stuffed-bear",
    title: "Giant Stuffed Teddy Bear",
    price: 59,
    strikePrice: 99,
    discount: "40% OFF",
    category: "toys",
    image: "🧸",
    badge: "Popular",
    rating: 4.7,
    inStock: true,
  },
  {
    id: "43",
    slug: "rc-car",
    title: "Remote Control Racing Car",
    price: 89,
    strikePrice: 149,
    discount: "40% OFF",
    category: "toys",
    image: "🚗",
    rating: 4.6,
    inStock: true,
  },
  {
    id: "44",
    slug: "puzzle-set",
    title: "Educational Puzzle Set - 3 in 1",
    price: 35,
    strikePrice: 59,
    discount: "41% OFF",
    category: "toys",
    image: "🧩",
    rating: 4.5,
    inStock: true,
  },
  {
    id: "45",
    slug: "toy-robot",
    title: "Interactive Robot Toy",
    price: 99,
    strikePrice: 169,
    discount: "41% OFF",
    category: "toys",
    image: "🤖",
    badge: "New Arrival",
    rating: 4.6,
    inStock: true,
  },
  {
    id: "46",
    slug: "play-kitchen",
    title: "Kids Play Kitchen Set",
    price: 129,
    strikePrice: 219,
    discount: "41% OFF",
    category: "toys",
    image: "🍽️",
    rating: 4.7,
    inStock: true,
  },
  {
    id: "47",
    slug: "toy-train",
    title: "Electric Train Set with Tracks",
    price: 79,
    strikePrice: 129,
    discount: "39% OFF",
    category: "toys",
    image: "🚂",
    rating: 4.5,
    inStock: true,
  },
  {
    id: "48",
    slug: "art-set",
    title: "Complete Art & Craft Set for Kids",
    price: 45,
    strikePrice: 79,
    discount: "43% OFF",
    category: "toys",
    image: "🎨",
    rating: 4.4,
    inStock: true,
  },

  // Books
  {
    id: "49",
    slug: "fiction-bestseller",
    title: "Bestselling Fiction Novel Collection",
    price: 39,
    strikePrice: 69,
    discount: "43% OFF",
    category: "books",
    image: "📚",
    badge: "Best Seller",
    rating: 4.8,
    inStock: true,
  },
  {
    id: "50",
    slug: "self-help-book",
    title: "Personal Development Book Set",
    price: 49,
    strikePrice: 89,
    discount: "45% OFF",
    category: "books",
    image: "📖",
    rating: 4.7,
    inStock: true,
  },
  {
    id: "51",
    slug: "cookbook",
    title: "Complete Cooking Guide - 500 Recipes",
    price: 45,
    strikePrice: 79,
    discount: "43% OFF",
    category: "books",
    image: "🍳",
    rating: 4.6,
    inStock: true,
  },
  {
    id: "52",
    slug: "childrens-books",
    title: "Children's Story Book Collection",
    price: 35,
    strikePrice: 59,
    discount: "41% OFF",
    category: "books",
    image: "📕",
    badge: "Popular",
    rating: 4.7,
    inStock: true,
  },
  {
    id: "53",
    slug: "science-book",
    title: "Science & Technology Encyclopedia",
    price: 59,
    strikePrice: 99,
    discount: "40% OFF",
    category: "books",
    image: "🔬",
    rating: 4.5,
    inStock: true,
  },
  {
    id: "54",
    slug: "history-book",
    title: "World History Complete Collection",
    price: 69,
    strikePrice: 119,
    discount: "42% OFF",
    category: "books",
    image: "📜",
    rating: 4.6,
    inStock: true,
  },
  {
    id: "55",
    slug: "biography",
    title: "Inspiring Biography Collection",
    price: 39,
    strikePrice: 69,
    discount: "43% OFF",
    category: "books",
    image: "📰",
    rating: 4.5,
    inStock: true,
  },
  {
    id: "56",
    slug: "comic-books",
    title: "Superhero Comic Book Bundle",
    price: 49,
    strikePrice: 89,
    discount: "45% OFF",
    category: "books",
    image: "💥",
    badge: "Hot Deal",
    rating: 4.8,
    inStock: true,
  },

  // Gaming
  {
    id: "57",
    slug: "gaming-controller",
    title: "Wireless Gaming Controller Pro",
    price: 79,
    strikePrice: 129,
    discount: "39% OFF",
    category: "gaming",
    image: "🎮",
    badge: "Best Seller",
    rating: 4.7,
    inStock: true,
  },
  {
    id: "58",
    slug: "gaming-headset",
    title: "7.1 Surround Gaming Headset",
    price: 129,
    strikePrice: 219,
    discount: "41% OFF",
    category: "gaming",
    image: "🎧",
    badge: "Popular",
    rating: 4.8,
    inStock: true,
  },
  {
    id: "59",
    slug: "gaming-chair",
    title: "Ergonomic Gaming Chair with RGB",
    price: 299,
    strikePrice: 499,
    discount: "40% OFF",
    category: "gaming",
    image: "🪑",
    badge: "Premium",
    rating: 4.6,
    inStock: true,
  },
  {
    id: "60",
    slug: "gaming-mouse-pad",
    title: "XXL RGB Gaming Mouse Pad",
    price: 39,
    strikePrice: 69,
    discount: "43% OFF",
    category: "gaming",
    image: "🖱️",
    rating: 4.5,
    inStock: true,
  },
  {
    id: "61",
    slug: "vr-headset",
    title: "Virtual Reality VR Headset",
    price: 349,
    strikePrice: 599,
    discount: "42% OFF",
    category: "gaming",
    image: "🥽",
    badge: "New Arrival",
    rating: 4.7,
    inStock: true,
  },
  {
    id: "62",
    slug: "gaming-monitor",
    title: '27" 144Hz Gaming Monitor',
    price: 399,
    strikePrice: 699,
    discount: "43% OFF",
    category: "gaming",
    image: "🖥️",
    badge: "Hot Deal",
    rating: 4.8,
    inStock: true,
  },
  {
    id: "63",
    slug: "capture-card",
    title: "4K Capture Card for Streaming",
    price: 179,
    strikePrice: 299,
    discount: "40% OFF",
    category: "gaming",
    image: "📹",
    rating: 4.6,
    inStock: true,
  },
  {
    id: "64",
    slug: "gaming-desk",
    title: "Gaming Desk with Cable Management",
    price: 249,
    strikePrice: 419,
    discount: "41% OFF",
    category: "gaming",
    image: "🎯",
    rating: 4.5,
    inStock: true,
  },
];

// Helper functions
export const getProductsByCategory = (category: string): Product[] => {
  return products.filter((p) => p.category === category);
};

export const getProductBySlug = (slug: string): Product | undefined => {
  return products.find((p) => p.slug === slug);
};

export const getFeaturedProducts = (limit: number = 12): Product[] => {
  return products.filter((p) => p.badge).slice(0, limit);
};

export const getNewArrivals = (limit: number = 12): Product[] => {
  return products.filter((p) => p.badge === "New Arrival").slice(0, limit);
};

export const getBestSellers = (limit: number = 12): Product[] => {
  return products.filter((p) => p.badge === "Best Seller").slice(0, limit);
};
